#!/bin/sh
# Generate this board's BCM84328 retimer tuning from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# Each 40G QSFP cage on this board sits behind a BCM84328 retimer. Bringing one
# up takes two different kinds of knowledge, and only the first is ours.
#
# The first is which bit turns the thing on: PMA vendor register 1.0xc8e4 bit
# 15, clear at power-up. That is the same on every board carrying the part, so
# the datapath sets it unconditionally and this script has nothing to say about
# it. Without it a cage configures cleanly, reports SR4 and 40000, and never
# links.
#
# The second is how the part is TUNED for this board's PCB traces, and that is
# vendor-derived exactly like the port map and the SerDes polarity. So NOSaic
# ships this generator and not its output.
#
# ⚠ TAKE THE CAPTURE BEFORE YOU INSTALL NOSAIC -- same irreversible ordering
# constraint as mkportmap.sh, and for the same reason: installing replaces the
# disk and the vendor's SDK goes with it.
#
# HOW THE REGISTERS WERE IDENTIFIED, SO THE NEXT PERSON CAN REDO IT
#
# There is no datasheet for this part. The list below came from a correlation:
# dump the PMA vendor block under NX-OS with a cage UP, dump it under NOSaic
# with the same cage UP, diff, and keep only what still differs. Doing the diff
# with our side DOWN is what misleads -- most of the differences are then
# status that differs BECAUSE the link is up, and two of them (0xc804, 0xc81f)
# are read-only status that come to match on their own once the link is
# established. Those two also silently swallow writes, which reads like a
# locked register and is not.
#
# ⚠ RUN THIS UNDER NX-OS, NOT UNDER NOSaic.
#
#   switch# configure terminal
#   switch(config)# feature bash-shell
#   switch(config)# end
#   switch# run bash
#   bash-4.2$ sh mkretimer.sh > retimer.conf
#
# Then copy retimer.conf into platform/cisco-n3172tq/config/ before building.
# It is gitignored: it is your board's data, not ours to publish.
set -eu

SHELL_BIN=/isan/bin/bcm-sdk-shell

# The six cage primaries, as logical port and as the SDK's own port name.
# Logical N is xe(N-1); the cages are four logical ports apart because each
# one occupies all four lanes of its core.
CAGES="49:xe48 53:xe52 57:xe56 61:xe60 65:xe64 69:xe68"

# The registers worth carrying. Everything else in the block either matches
# already or is status. Keep this list short on purpose: a register written
# for no reason is a register someone has to justify later.
REGS="0xc80e 0xc876 0xc87c"

echo "# BCM84328 retimer tuning for one physical Cisco Nexus 3172TQ."
echo "# Generated by mkretimer.sh from this switch's own NX-OS. Do not commit."
echo "#"
echo "# One line per cage per register. A cage with no lines is left at the"
echo "# part's power-up defaults, which is a working link and an untuned one."
echo ""

for c in $CAGES; do
	port=${c%%:*}
	name=${c##*:}

	# A cage with no module fitted reports nothing useful, and tuning read
	# off a dark cage is not tuning. Skip it rather than record defaults.
	if ! echo "ps $name" | sudo $SHELL_BIN 2>/dev/null | grep -q "$name  *up"; then
		echo "# $name (logical $port): link down at capture time, skipped."
		continue
	fi

	for r in $REGS; do
		# `phy <name> 0x01<reg>` prints one line per MMD; DevAd 1 is the
		# PMA/PMD, which is where all of these live.
		v=$(printf 'phy %s 0x01%04x\n' "$name" "$r" \
			| sudo $SHELL_BIN 2>/dev/null \
			| awk '/DevAd 1\(/ { print $NF; exit }')
		[ -n "$v" ] || continue
		echo "retimer_84328_${port}_${r}=${v}"
	done
	echo ""
done
