// Package svcgen turns abstract service definitions into init-system files.
//
// Recipes never write unit files. They declare what a service is — what to
// run, and what must be running first — and both a systemd unit and an s6-rc
// definition are generated from that.
//
// The reason is the minimal profile, which runs busybox and s6 rather than
// systemd on boards too small for it. If recipes shipped unit files, every
// recipe that starts a daemon would need a second hand-written copy, they
// would drift, and the small-board tier would quietly rot. Generating both
// from one declaration means a recipe author cannot forget the tier they do
// not personally use.
package svcgen

import (
	"fmt"
	"path"
	"sort"
	"strings"
)

// Service is the abstract declaration, mirroring the recipe stanza.
type Service struct {
	Name    string
	Exec    string
	After   []string
	Wants   []string
	Restart string // "" (default: on-failure), "always", "never"
}

// File is one generated file to install.
type File struct {
	Path    string
	Mode    uint32
	Content string
}

// Backend generates files for one init system.
type Backend interface {
	// ID is the init system's name, as used in a profile.
	ID() string
	Generate(s Service) ([]File, error)
}

// For returns the backend for an init system.
func For(init string) (Backend, error) {
	switch init {
	case "systemd":
		return systemd{}, nil
	case "s6":
		return s6{}, nil
	default:
		return nil, fmt.Errorf("svcgen: unknown init system %q (known: systemd, s6)", init)
	}
}

// All returns every backend. Packages generate for all of them, because a
// package is built once and may be composed into images of any profile.
func All() []Backend { return []Backend{systemd{}, s6{}} }

// Validate rejects a declaration that cannot be expressed in every backend,
// so the failure lands on the recipe author rather than on whoever first
// builds a minimal image months later.
func (s Service) Validate() error {
	if s.Name == "" {
		return fmt.Errorf("service name is required")
	}
	if strings.ContainsAny(s.Name, " \t/\n") {
		return fmt.Errorf("service name %q may not contain spaces, slashes or newlines", s.Name)
	}
	if s.Exec == "" {
		return fmt.Errorf("service %q: exec is required", s.Name)
	}
	if strings.ContainsAny(s.Exec, "\n\r") {
		return fmt.Errorf("service %q: exec may not contain newlines", s.Name)
	}
	if !path.IsAbs(strings.Fields(s.Exec)[0]) {
		return fmt.Errorf("service %q: exec must start with an absolute path, got %q",
			s.Name, strings.Fields(s.Exec)[0])
	}
	switch s.Restart {
	case "", "on-failure", "always", "never":
	default:
		return fmt.Errorf("service %q: restart %q must be one of on-failure, always, never",
			s.Name, s.Restart)
	}
	return nil
}

func sorted(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}

// ---------------------------------------------------------------- systemd

type systemd struct{}

func (systemd) ID() string { return "systemd" }

func (systemd) Generate(s Service) ([]File, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString("# Generated by nosaic from the recipe's services: stanza.\n")
	b.WriteString("# Do not edit: regenerate the package instead.\n\n")
	b.WriteString("[Unit]\n")
	fmt.Fprintf(&b, "Description=%s\n", s.Name)
	if len(s.After) > 0 {
		fmt.Fprintf(&b, "After=%s\n", strings.Join(unitNames(sorted(s.After)), " "))
	}
	if len(s.Wants) > 0 {
		fmt.Fprintf(&b, "Wants=%s\n", strings.Join(unitNames(sorted(s.Wants)), " "))
	}
	b.WriteString("\n[Service]\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", s.Exec)
	switch s.Restart {
	case "never":
		b.WriteString("Restart=no\n")
	case "always":
		b.WriteString("Restart=always\nRestartSec=5\n")
	default:
		b.WriteString("Restart=on-failure\nRestartSec=5\n")
	}
	b.WriteString("\n[Install]\nWantedBy=multi-user.target\n")

	return []File{{
		Path:    "/usr/lib/systemd/system/" + s.Name + ".service",
		Mode:    0o644,
		Content: b.String(),
	}}, nil
}

// unitNames appends .service to bare names. "network" and other well-known
// targets are left alone.
func unitNames(in []string) []string {
	out := make([]string, len(in))
	for i, n := range in {
		switch {
		case strings.Contains(n, "."):
			out[i] = n // already qualified: foo.service, network.target
		case n == "network" || n == "basic" || n == "sysinit" || n == "multi-user":
			out[i] = n + ".target"
		default:
			out[i] = n + ".service"
		}
	}
	return out
}

// --------------------------------------------------------------------- s6

type s6 struct{}

func (s6) ID() string { return "s6" }

func (s6) Generate(s Service) ([]File, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	dir := "/etc/s6-rc/source/" + s.Name

	files := []File{
		{Path: dir + "/type", Mode: 0o644, Content: "longrun\n"},
		{
			Path: dir + "/run",
			Mode: 0o755,
			Content: "#!/bin/sh\n" +
				"# Generated by nosaic from the recipe's services: stanza.\n" +
				"# Do not edit: regenerate the package instead.\n" +
				"exec 2>&1\n" +
				"exec " + s.Exec + "\n",
		},
	}

	// s6-rc expresses ordering with an empty file per dependency. systemd's
	// After and Wants collapse to the same thing here, because s6-rc has one
	// notion of dependency rather than separate ordering and wanting.
	deps := map[string]bool{}
	for _, d := range append(append([]string(nil), s.After...), s.Wants...) {
		deps[bareName(d)] = true
	}
	names := make([]string, 0, len(deps))
	for d := range deps {
		names = append(names, d)
	}
	for _, d := range sorted(names) {
		files = append(files, File{
			Path: dir + "/dependencies.d/" + d, Mode: 0o644, Content: "",
		})
	}

	if s.Restart == "never" {
		files = append(files, File{Path: dir + "/down-signal", Mode: 0o644, Content: "SIGTERM\n"})
	}
	return files, nil
}

// bareName strips a systemd-style suffix, since s6 dependency names have none.
func bareName(n string) string {
	for _, suf := range []string{".service", ".target", ".socket"} {
		if strings.HasSuffix(n, suf) {
			return strings.TrimSuffix(n, suf)
		}
	}
	return n
}
