// Package docsgen renders the switch index from the board directories.
//
// It is generated rather than written because the board directories are the
// truth. A hand-maintained index is a shared file every board port has to
// edit, which is both a merge conflict between contributors and a thing that
// silently goes stale -- the two problems the self-contained board directory
// exists to avoid.
package docsgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/salvaged-silicon/nosaic-switch/internal/board"
	"github.com/salvaged-silicon/nosaic-switch/internal/boot"
)

// Path is where the rendered index lives, relative to the repo root.
const Path = "docs/switches.md"

const header = `<!-- Generated by ` + "`make docs`" + ` from the board directories. Do not edit. -->

# Supported switches

Each board is one self-contained directory under ` + "`platform/`" + `. This page is
generated from them, so a new port is added by adding a directory and never by
editing a shared file.

Every board carries **install** for somebody holding the switch, **build** for
somebody making an image, **hardware** for somebody changing the datapath or
debugging silicon, and **todo** for what is left. A board that has been brought
up on real hardware also carries a **walkthrough** — the ordered path from a
switch in a rack to one that forwards, and where to start if you have one.

`

// pageOrder is the order pages are listed in when a board has them. Anything
// a board ships that is not named here follows, alphabetically -- the point is
// a predictable order for the common pages, not a list to keep in step with
// what boards actually contain.
var pageOrder = []string{
	"walkthrough", "install", "running", "build", "architecture", "hardware", "todo",
}

// pageLinks lists the documentation a board actually has.
//
// Enumerated rather than assumed. A fixed list here means a board that adds a
// page does not get it linked, and the whole reason this file is generated is
// that the board directory is the truth. A board missing one of the common
// pages is likewise reported as it is rather than linked into a 404.
func pageLinks(bd *board.Board, dir string) string {
	docs := filepath.Join(filepath.Dir(bd.Path), "docs")
	entries, err := os.ReadDir(docs)
	if err != nil {
		return "—"
	}

	have := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		have[strings.TrimSuffix(e.Name(), ".md")] = true
	}

	var names []string
	for _, n := range pageOrder {
		if have[n] {
			names = append(names, n)
			delete(have, n)
		}
	}
	var rest []string
	for n := range have {
		rest = append(rest, n)
	}
	sort.Strings(rest)
	names = append(names, rest...)

	var links []string
	for _, n := range names {
		links = append(links, fmt.Sprintf("[%s](%s/docs/%s.md)", n, dir, n))
	}
	return strings.Join(links, " · ")
}

// Render returns the index for the given boards.
func Render(boards []*board.Board) string {
	var b strings.Builder
	b.WriteString(header)

	if len(boards) == 0 {
		b.WriteString("No boards are merged yet.\n")
		return b.String()
	}

	b.WriteString("| Board | Arch | ASIC | Boot | Status | Pages |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, bd := range boards {
		dir := filepath.ToSlash(filepath.Join("..", "platform", bd.ID))
		pages := pageLinks(bd, dir)
		fmt.Fprintf(&b, "| [%s](%s/README.md) | %s | %s | %s | %s | %s |\n",
			bd.ID, dir, bd.Arch, bd.ASIC, bd.Boot, bd.Status, pages)
	}

	b.WriteString("\n## How each board installs\n\n")
	seen := map[string]bool{}
	for _, bd := range boards {
		if seen[bd.Boot] {
			continue
		}
		seen[bd.Boot] = true
		desc := bd.Boot
		if be, err := boot.For(bd.Boot); err == nil {
			desc = be.Describe()
		}
		fmt.Fprintf(&b, "- **%s** — %s\n", bd.Boot, desc)
	}

	writeGenerators(&b, boards)
	return b.String()
}

// writeGenerators lists the per-switch data a board cannot ship and how to
// produce it.
//
// Some boards need numbers that are only readable from the vendor's own
// software on the machine that has them -- a SerDes port map, a polarity
// table. Those are not in this repository, and a catalog that merely omits
// them reads as though the board is unsupported. It is the opposite: the
// generator is the supported part, and the output is yours.
//
// Derived from the board directory like everything else here, so a port that
// adds a generator gets it listed without editing this file.
func writeGenerators(b *strings.Builder, boards []*board.Board) {
	type entry struct {
		id    string
		tools []string
	}
	var have []entry
	for _, bd := range boards {
		if bd.Path == "" {
			continue
		}
		dir := filepath.Join(filepath.Dir(bd.Path), "tools")
		ents, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		var names []string
		for _, e := range ents {
			if !e.IsDir() {
				names = append(names, e.Name())
			}
		}
		if len(names) > 0 {
			sort.Strings(names)
			have = append(have, entry{bd.ID, names})
		}
	}
	if len(have) == 0 {
		return
	}

	b.WriteString("\n## Boards that need data from the vendor's OS\n\n")
	b.WriteString("A few boards need numbers that no public document publishes and that can\n")
	b.WriteString("only be read from the vendor's software on a machine that already has them\n")
	b.WriteString("— which SerDes lane each port is wired to, which lanes have their pair\n")
	b.WriteString("swapped on the PCB. That output is yours rather than ours, so it is **not in\n")
	b.WriteString("this repository**. The generators are, and they are read-only against the\n")
	b.WriteString("switch:\n\n")

	for _, e := range have {
		dir := filepath.ToSlash(filepath.Join("..", "platform", e.id))
		fmt.Fprintf(b, "- **%s** — [tools/](%s/tools/): ", e.id, dir)
		for i, n := range e.tools {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(b, "`%s`", n)
		}
		fmt.Fprintf(b, "\n  Run them once against a switch running the vendor's OS, drop the output\n"+
			"  in [config/](%s/config/), and it ships in every image you build for that\n"+
			"  board. Full instructions are in that board's README.\n", dir)
	}
}

// Write renders the index into the repository.
func Write(root string, boards []*board.Board) error {
	p := filepath.Join(root, Path)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, []byte(Render(boards)), 0o644)
}

// Stale reports whether the checked-in index differs from what the board
// directories would produce, and is what keeps "generated" from meaning
// "generated once, months ago".
func Stale(root string, boards []*board.Board) (bool, error) {
	got, err := os.ReadFile(filepath.Join(root, Path))
	if os.IsNotExist(err) {
		// A repo with no boards and no index is consistent, not stale. The
		// point of this check is that the index and the board directories
		// agree, and with neither present there is nothing to disagree about.
		return len(boards) > 0, nil
	}
	if err != nil {
		return false, err
	}
	return string(got) != Render(boards), nil
}
