// Package docsgen renders the switch index from the board directories.
//
// It is generated rather than written because the board directories are the
// truth. A hand-maintained index is a shared file every board port has to
// edit, which is both a merge conflict between contributors and a thing that
// silently goes stale -- the two problems the self-contained board directory
// exists to avoid.
package docsgen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/salvaged-silicon/nosaic-switch/internal/board"
	"github.com/salvaged-silicon/nosaic-switch/internal/boot"
)

// Path is where the rendered index lives, relative to the repo root.
const Path = "docs/switches.md"

const header = `<!-- Generated by ` + "`make docs`" + ` from the board directories. Do not edit. -->

# Supported switches

Each board is one self-contained directory under ` + "`platform/`" + `. This page is
generated from them, so a new port is added by adding a directory and never by
editing a shared file.

Every board has three pages: **install** for somebody holding the switch,
**build** for somebody making an image, and **hardware** for somebody changing
the datapath or debugging silicon.

`

// Render returns the index for the given boards.
func Render(boards []*board.Board) string {
	var b strings.Builder
	b.WriteString(header)

	if len(boards) == 0 {
		b.WriteString("No boards are merged yet.\n")
		return b.String()
	}

	b.WriteString("| Board | Arch | ASIC | Boot | Status | Pages |\n")
	b.WriteString("|---|---|---|---|---|---|\n")
	for _, bd := range boards {
		dir := filepath.ToSlash(filepath.Join("..", "platform", bd.ID))
		pages := fmt.Sprintf("[install](%s/docs/install.md) · [build](%s/docs/build.md) · [hardware](%s/docs/hardware.md)",
			dir, dir, dir)
		fmt.Fprintf(&b, "| [%s](%s/README.md) | %s | %s | %s | %s | %s |\n",
			bd.ID, dir, bd.Arch, bd.ASIC, bd.Boot, bd.Status, pages)
	}

	b.WriteString("\n## How each board installs\n\n")
	seen := map[string]bool{}
	for _, bd := range boards {
		if seen[bd.Boot] {
			continue
		}
		seen[bd.Boot] = true
		desc := bd.Boot
		if be, err := boot.For(bd.Boot); err == nil {
			desc = be.Describe()
		}
		fmt.Fprintf(&b, "- **%s** — %s\n", bd.Boot, desc)
	}
	return b.String()
}

// Write renders the index into the repository.
func Write(root string, boards []*board.Board) error {
	p := filepath.Join(root, Path)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	return os.WriteFile(p, []byte(Render(boards)), 0o644)
}

// Stale reports whether the checked-in index differs from what the board
// directories would produce, and is what keeps "generated" from meaning
// "generated once, months ago".
func Stale(root string, boards []*board.Board) (bool, error) {
	got, err := os.ReadFile(filepath.Join(root, Path))
	if os.IsNotExist(err) {
		// A repo with no boards and no index is consistent, not stale. The
		// point of this check is that the index and the board directories
		// agree, and with neither present there is nothing to disagree about.
		return len(boards) > 0, nil
	}
	if err != nil {
		return false, err
	}
	return string(got) != Render(boards), nil
}
