#!/bin/sh
# Generate this board's PHY wiring from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# The SDK cannot reach a front-panel copper port without knowing which MDIO
# address that port's external PHY answers on. There are 48 of them here, on
# six BCM54282 octal parts, and no public document says where any of them sit.
#
# So it has to be read from the vendor's software on a switch that has it. That
# makes the result vendor-derived, which is why NOSaic ships this generator and
# not its output: you run it once against your own switch and the map stays
# yours. Everything that is *not* vendor-derived -- the port bitmaps, the table
# sizes, the bring-up knobs -- is in config/asic.conf and ships.
#
# WHY GUESSING DOES NOT WORK
#
# The addresses look perfectly regular, which is the trap. Six primaries at
# 0x01, 0x09, 0x11, 0x19, 0x21 and 0x29, each covering eight ports at offsets
# 0..7, giving 0x01..0x30 straight through -- and then ge11 is at 0x0e where
# the arithmetic says 0x0c. One exception in forty-eight.
#
# Getting one wrong does not fail. The SDK talks to a real PHY that belongs to
# a different socket, so a port reports another port's link state and carries
# another port's autonegotiation. Nothing errors, and the symptom appears days
# later as a cable that "does not work in that hole".
#
# WHAT IT EMITS
#
#   port_phy_addr_ge<n>                where each copper PHY answers
#   phy_port_primary_and_offset_ge<n>  which octal part and which of its eight
#   port_phy_addr_xe<n>                the four SFP+ PHYs
#   phy_fiber_pref_xe<n>               fibre rather than copper on those cages
#   phy_automedium_xe<n>               and no media autoselection
#
# HOW TO RUN IT
#
# On a switch still running its vendor OS -- stock Edgecore FASTPATH/ICOS, ONL,
# Cumulus or EdgeNOS, any of which keep a config.bcm:
#
#     ./mkphymap.sh /path/to/config.bcm > phymap.conf
#
# or over ssh, which is what it does with no argument:
#
#     ./mkphymap.sh root@myswitch > phymap.conf
#
# Then drop phymap.conf in ../config/ and it ships in every image you build for
# this board. It is read-only against the switch: it reads one file.
set -eu

usage() {
    echo "usage: $0 <config.bcm | user@host>" >&2
    echo "  reads the vendor's config.bcm and writes a NOSaic phymap.conf to stdout" >&2
    exit 2
}

[ $# -eq 1 ] || usage
src="$1"

if [ -f "$src" ]; then
    bcm=$(cat "$src")
else
    # The usual places a vendor OS keeps it. First hit wins.
    bcm=$(ssh "$src" 'for f in /opt/edgenos/config.bcm /etc/bcm/config.bcm \
                              /usr/local/edgenos/config.bcm \
                              /lib/platform-config/current/onl/*/config.bcm \
                              /etc/config.bcm; do
              [ -r "$f" ] && { cat "$f"; exit 0; }
          done
          echo "no config.bcm found on this switch" >&2; exit 1') || exit 1
fi

[ -n "$bcm" ] || { echo "$0: read nothing from $src" >&2; exit 1; }

# Only the port-keyed PHY properties, and nothing else in the file. The rest of
# config.bcm is chip behaviour that config/asic.conf already states in NOSaic's
# own terms; copying it wholesale would ship the vendor's tuning under our name
# and would silently override what asic.conf says, since both are loaded.
#
# The unit suffix is stripped. Broadcom writes `phy_5464S_xe0.0`; the SDK asks
# config_var_get for the bare name and never matches a suffixed one.
emit=$(printf '%s\n' "$bcm" \
    | sed 's/[[:space:]]*#.*$//; s/\.0=/=/' \
    | grep -E '^(port_phy_addr|phy_port_primary_and_offset|phy_fiber_pref|phy_automedium)_(ge|xe)[0-9]+=' \
    | sort -t= -k1,1V)

[ -n "$emit" ] || { echo "$0: no PHY properties in that config.bcm" >&2; exit 1; }

cat <<EOF
# NOT IN GIT. Where each front-panel port's external PHY answers on MDIO.
#
# Generated by platform/edgecore-as4610-54t/tools/mkphymap.sh from a switch
# running its vendor OS, on $(date -u +%Y-%m-%d), so the numbers are the
# vendor's. Board data rather than per-unit data, so it belongs in the image
# you build -- the image builder copies platform/<board>/config/ into
# /etc/nosaic, where the datapath looks for it.
#
# Source: $src
# $(printf '%s\n' "$emit" | wc -l) properties.

$emit
EOF
