package imgbuild

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// initScript is the first userspace the machine runs.
//
// Its whole job is to get from "the kernel has started" to "the real root is
// mounted and init is running". It selects an A/B slot, mounts that image
// read-only, puts the slot's persistent writable layer over it, and hands over.
//
// It is deliberately small and deliberately loud. An initramfs that fails
// silently leaves a machine that appears hung with no explanation, and on a
// switch in a rack the console is often the only diagnostic there is.
const initScript = `#!/bin/sh
# Generated by nosaic. The initramfs: pick a slot, mount it, overlay it, hand over.

fail() {
    echo
    echo "NOSAIC-INITRAMFS-FAIL $*"
    echo "dropping to a shell; the image was not mounted"
    exec /bin/sh
}

/bin/busybox --install -s /bin 2>/dev/null

mkdir -p /proc /sys /dev /mnt/image /mnt/data /mnt/root
mount -t proc     proc     /proc  || fail "cannot mount /proc"
mount -t sysfs    sysfs    /sys   || fail "cannot mount /sys"
mount -t devtmpfs devtmpfs /dev   || fail "cannot mount /dev"

echo "NOSAIC-INITRAMFS starting"

# A rootfs carried inside the initramfs, for booting with no NOSaic partitions
# at all. That is how a switch is tried before anything is written to it:
# Aboot's "boot --testonly <url>" fetches the image over the network into RAM,
# so the flash still holds the vendor's layout and there is no slot to find.
#
# Checked before anything probes storage. Doing it afterwards still worked, but
# printed two warnings about missing partitions first -- on a boot where their
# absence is the entire intention. Warnings that are expected teach an operator
# to ignore warnings.
if [ -f /nosaic-rootfs.sqsh ]; then
    echo "NOSAIC-INITRAMFS booting from RAM, no partitions used"
    mount -t squashfs -o ro,loop /nosaic-rootfs.sqsh /mnt/image \
        || fail "the embedded rootfs will not mount"
    echo "NOSAIC-INITRAMFS image mounted"
    echo "NOSAIC-BOOT-SLOT ram"
    mount -t tmpfs tmpfs /mnt/data 2>/dev/null || true
    mkdir -p /mnt/data/slot-ram/upper/etc/nosaic /mnt/data/slot-ram/work
    # Tells the booted system it has no persistence by design, so its self-test
    # does not report the absence as a fault.
    : > /mnt/data/slot-ram/upper/etc/nosaic/ramboot
    mount -t overlay overlay \
        -o lowerdir=/mnt/image,upperdir=/mnt/data/slot-ram/upper,workdir=/mnt/data/slot-ram/work \
        /mnt/root || fail "cannot assemble the overlay"
    echo "NOSAIC-INITRAMFS overlay assembled (persistent=no)"
    [ -x /mnt/root/sbin/init ] || fail "the image has no /sbin/init"
    echo "NOSAIC-BOOT userspace reached (ram)"
    echo "NOSAIC-INITRAMFS handing over to /sbin/init"
    exec switch_root /mnt/root /sbin/init || fail "switch_root failed"
fi

# The persistent partition comes first, because the slot decision is recorded
# there. A switch that cannot read it still boots: it falls back to slot A
# stateless rather than sitting in an initramfs shell in a rack somewhere.
# The slot pointer, on its own journal-less filesystem. Read before anything
# else, because it decides what gets mounted.
mkdir -p /mnt/boot
BOOTDEV="$(findfs LABEL=nosaic-boot 2>/dev/null || echo /dev/vda1)"
if mount -t ext2 "$BOOTDEV" /mnt/boot 2>/dev/null; then
    B=/mnt/boot/boot
    mkdir -p $B
else
    echo "NOSAIC-INITRAMFS-WARN no boot partition; defaulting to slot a"
    B=/tmp/boot
    mkdir -p $B
fi

PERSIST=no
DATA="$(findfs LABEL=nosaic-data 2>/dev/null || echo /dev/vda4)"
if mount -t ext4 "$DATA" /mnt/data 2>/dev/null; then
    echo "NOSAIC-INITRAMFS data partition mounted ($DATA)"
    mkdir -p /mnt/data/config /mnt/data/secrets
    PERSIST=yes
else
    echo "NOSAIC-INITRAMFS-WARN no data partition; booting stateless"
    mount -t tmpfs tmpfs /mnt/data || fail "cannot mount a fallback writable layer"
fi

# Slots are found by label first. The device names below are a fallback for a
# disk that has our partitions but no readable labels, and they are guesses:
# virtio on a VM, SCSI/SATA on most switches, eMMC on some. Naming one disk
# would have been wrong on every board that is not that disk.
slotdev() {
    local want=""
    case "$1" in
        a) want=nosaic-slot-a ;;
        b) want=nosaic-slot-b ;;
        *) echo ""; return ;;
    esac
    findfs "LABEL=$want" 2>/dev/null && return
    local n=""
    case "$1" in a) n=2 ;; b) n=3 ;; esac
    for d in /dev/vda /dev/sda /dev/mmcblk0p; do
        case "$d" in
            /dev/mmcblk0p) [ -b "$d$n" ] && { echo "$d$n"; return; } ;;
            *)             [ -b "$d$n" ] && { echo "$d$n"; return; } ;;
        esac
    done
    echo ""
}

ACTIVE="$(cat $B/active 2>/dev/null || echo a)"
TRIAL="$(cat $B/trial  2>/dev/null || echo '')"
TRIES="$(cat $B/tries  2>/dev/null || echo 0)"
MAXTRIES=3

# A command-line override wins, for recovery and for testing. It is never
# written back, so it cannot accidentally become the committed choice.
for arg in $(cat /proc/cmdline); do
    case "$arg" in nosaic.slot=*) ACTIVE="${arg#nosaic.slot=}"; TRIAL="" ;; esac
done

SLOT="$ACTIVE"
if [ -n "$TRIAL" ]; then
    if [ "$TRIES" -ge "$MAXTRIES" ]; then
        # The trial slot booted but never confirmed itself healthy. An image
        # that starts and then does not work is exactly what rollback is for.
        echo "NOSAIC-BOOT-ROLLBACK slot $TRIAL failed to confirm after $TRIES attempts; returning to $ACTIVE"
        rm -f $B/trial $B/tries
    else
        TRIES=$((TRIES + 1))
        echo "$TRIES" > $B/tries 2>/dev/null
        SLOT="$TRIAL"
        echo "NOSAIC-BOOT-TRIAL slot $TRIAL attempt $TRIES of $MAXTRIES"
    fi
fi

SLOTDEV="$(slotdev "$SLOT")"
[ -n "$SLOTDEV" ] || fail "unknown slot '$SLOT'"
echo "NOSAIC-INITRAMFS slot $SLOT ($SLOTDEV)"

if ! mount -t squashfs -o ro "$SLOTDEV" /mnt/image 2>/dev/null; then
    # A trial slot that will not even mount is definitively bad. There is
    # nothing to learn from retrying it, so roll back at once rather than
    # spending the trial budget discovering the same thing three times.
    if [ "$SLOT" != "$ACTIVE" ]; then
        echo "NOSAIC-BOOT-ROLLBACK slot $SLOT does not contain a mountable image; returning to $ACTIVE"
        rm -f $B/trial $B/tries
        SLOT="$ACTIVE"
        SLOTDEV="$(slotdev "$SLOT")"
        mount -t squashfs -o ro "$SLOTDEV" /mnt/image || fail "slot $ACTIVE is unmountable too; there is nothing left to boot"
    else
        fail "slot $SLOT does not contain a mountable image"
    fi
fi
echo "NOSAIC-INITRAMFS image mounted"
echo "NOSAIC-BOOT-SLOT $SLOT"

UPPER="/mnt/data/slot-$SLOT/upper"
WORK="/mnt/data/slot-$SLOT/work"
mkdir -p "$UPPER" "$WORK"

mount -t overlay overlay \
    -o lowerdir=/mnt/image,upperdir=$UPPER,workdir=$WORK \
    /mnt/root || fail "cannot assemble the overlay"
echo "NOSAIC-INITRAMFS overlay assembled (persistent=$PERSIST)"

[ -x /mnt/root/sbin/init ] || fail "the image has no /sbin/init"

# Carry the data partition and the pseudo-filesystems into the real root, so
# the running system does not have to re-mount what is already mounted.
mkdir -p /mnt/root/mnt/data /mnt/root/mnt/boot
mount --move /mnt/data /mnt/root/mnt/data 2>/dev/null
mount --move /mnt/boot /mnt/root/mnt/boot 2>/dev/null
mount --move /dev /mnt/root/dev 2>/dev/null

echo "NOSAIC-INITRAMFS handing over to /sbin/init"
exec switch_root /mnt/root /sbin/init || fail "switch_root failed"
`

// buildInitramfs packs a busybox and the init script above into a cpio.
//
// busybox comes from the composed image rather than from a separate build, so
// the initramfs and the system it boots are the same binary — which is why
// that package is built static.
// buildInitramfs packs busybox, the init script, and — when embed is non-empty
// — the root filesystem itself.
//
// Embedding makes the image self-contained: kernel plus initramfs and nothing
// else, which is what a switch needs to be tried before anything is written to
// it. Aboot fetches such an image over the network and runs it from RAM, so
// there are no NOSaic partitions to find and the vendor's OS is still intact
// on flash.
//
// It is not the normal shape. An installed switch mounts its slot from flash;
// this exists so the first boot on a new board risks nothing.
func buildInitramfs(o Options, work, rootfs string, embed string) (string, error) {
	fmt.Fprintf(o.Log, "==> building the initramfs\n")
	dir := filepath.Join(work, "initramfs")
	for _, d := range []string{"bin", "sbin", "proc", "sys", "dev", "mnt"} {
		if err := os.MkdirAll(filepath.Join(dir, d), 0o755); err != nil {
			return "", err
		}
	}

	bb := filepath.Join(rootfs, "bin", "busybox")
	if _, err := os.Stat(bb); err != nil {
		return "", fmt.Errorf("the image has no /bin/busybox, so no initramfs can be built: %w", err)
	}
	if err := copyFile(bb, filepath.Join(dir, "bin", "busybox")); err != nil {
		return "", err
	}
	if err := os.Chmod(filepath.Join(dir, "bin", "busybox"), 0o755); err != nil {
		return "", err
	}
	for _, link := range []string{"sh", "mount", "mkdir", "switch_root", "echo"} {
		_ = os.Symlink("busybox", filepath.Join(dir, "bin", link))
	}
	if err := os.WriteFile(filepath.Join(dir, "init"), []byte(initScript), 0o755); err != nil {
		return "", err
	}

	// The root filesystem, carried inside, when this image is meant to boot
	// without touching storage. Copied rather than linked: the cpio has to
	// contain the bytes.
	if embed != "" {
		if err := copyFile(embed, filepath.Join(dir, "nosaic-rootfs.sqsh")); err != nil {
			return "", fmt.Errorf("embedding the root filesystem: %w", err)
		}
		fmt.Fprintf(o.Log, "    embedding the root filesystem for a RAM boot\n")
	}

	out := filepath.Join(o.OutDir, "initramfs.cpio.gz")
	// Sorted names and gzip -n keep this reproducible, like every other
	// artifact: find's traversal order and a gzip timestamp are exactly the
	// two things that would otherwise differ between builds.
	script := fmt.Sprintf(
		`cd %q && find . | LC_ALL=C sort | cpio -o -H newc --quiet --reproducible | gzip -9 -n > %q`,
		dir, out)
	cmd := exec.Command("sh", "-c", script)
	if b, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("packing the initramfs: %v\n%s", err, b)
	}
	return out, nil
}
