package imgbuild

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// initScript is the first userspace the machine runs.
//
// Its whole job is to get from "the kernel has started" to "the real root is
// mounted and init is running". It mounts the read-only image, puts a writable
// layer over it, and hands over.
//
// It is deliberately small and deliberately loud. An initramfs that fails
// silently leaves a machine that appears hung with no explanation, and on a
// switch in a rack the console is often the only diagnostic there is.
const initScript = `#!/bin/sh
# Generated by nosaic. The initramfs: mount the image, overlay it, hand over.

fail() {
    echo
    echo "NOSAIC-INITRAMFS-FAIL $*"
    echo "dropping to a shell; the image was not mounted"
    exec /bin/sh
}

/bin/busybox --install -s /bin 2>/dev/null

mkdir -p /proc /sys /dev /mnt/image /mnt/write /mnt/root
mount -t proc     proc     /proc  || fail "cannot mount /proc"
mount -t sysfs    sysfs    /sys   || fail "cannot mount /sys"
mount -t devtmpfs devtmpfs /dev   || fail "cannot mount /dev"

echo "NOSAIC-INITRAMFS starting"

# The image. Read-only and immutable by design: everything writable lives in
# the layer above, so the running system cannot modify what it booted from.
IMAGE=/dev/vda
[ -b "$IMAGE" ] || fail "no image device at $IMAGE"
mount -t squashfs -o ro "$IMAGE" /mnt/image || fail "cannot mount $IMAGE as squashfs"
echo "NOSAIC-INITRAMFS image mounted"

# The writable layer. This is tmpfs for now, which means changes do not
# survive a reboot; the persistent data partition replaces it, and that is
# also what makes config shared across A/B slots.
mount -t tmpfs tmpfs /mnt/write || fail "cannot mount the writable layer"
mkdir -p /mnt/write/upper /mnt/write/work

mount -t overlay overlay \
    -o lowerdir=/mnt/image,upperdir=/mnt/write/upper,workdir=/mnt/write/work \
    /mnt/root || fail "cannot assemble the overlay"
echo "NOSAIC-INITRAMFS overlay assembled"

[ -x /mnt/root/sbin/init ] || fail "the image has no /sbin/init"

# Move the pseudo-filesystems across rather than leaving them behind, so the
# real root does not have to re-mount what is already mounted.
mount --move /dev /mnt/root/dev 2>/dev/null

echo "NOSAIC-INITRAMFS handing over to /sbin/init"
exec switch_root /mnt/root /sbin/init || fail "switch_root failed"
`

// buildInitramfs packs a busybox and the init script above into a cpio.
//
// busybox comes from the composed image rather than from a separate build, so
// the initramfs and the system it boots are the same binary — which is why
// that package is built static.
func buildInitramfs(o Options, work, rootfs string) (string, error) {
	fmt.Fprintf(o.Log, "==> building the initramfs\n")
	dir := filepath.Join(work, "initramfs")
	for _, d := range []string{"bin", "sbin", "proc", "sys", "dev", "mnt"} {
		if err := os.MkdirAll(filepath.Join(dir, d), 0o755); err != nil {
			return "", err
		}
	}

	bb := filepath.Join(rootfs, "bin", "busybox")
	if _, err := os.Stat(bb); err != nil {
		return "", fmt.Errorf("the image has no /bin/busybox, so no initramfs can be built: %w", err)
	}
	if err := copyFile(bb, filepath.Join(dir, "bin", "busybox")); err != nil {
		return "", err
	}
	if err := os.Chmod(filepath.Join(dir, "bin", "busybox"), 0o755); err != nil {
		return "", err
	}
	for _, link := range []string{"sh", "mount", "mkdir", "switch_root", "echo"} {
		_ = os.Symlink("busybox", filepath.Join(dir, "bin", link))
	}
	if err := os.WriteFile(filepath.Join(dir, "init"), []byte(initScript), 0o755); err != nil {
		return "", err
	}

	out := filepath.Join(o.OutDir, "initramfs.cpio.gz")
	// Sorted names and gzip -n keep this reproducible, like every other
	// artifact: find's traversal order and a gzip timestamp are exactly the
	// two things that would otherwise differ between builds.
	script := fmt.Sprintf(
		`cd %q && find . | LC_ALL=C sort | cpio -o -H newc --quiet --reproducible | gzip -9 -n > %q`,
		dir, out)
	cmd := exec.Command("sh", "-c", script)
	if b, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("packing the initramfs: %v\n%s", err, b)
	}
	return out, nil
}
