package imgbuild

import (
	"fmt"
	"os"
	"path/filepath"
)

// writeNetwork installs the board's network configuration and the service that
// applies it.
//
// Until this existed an image booted with no addresses at all: iproute2 was in
// the profile and nothing ever called it. A switch that reaches a login and
// cannot be reached over the network is only half a switch, and on a box whose
// console is a serial cable in another building that difference matters.
//
// The configuration is the board's, not the image's, because addresses are a
// property of where the box is plugged in. It is applied by a generated
// service like everything else, so the same declaration works whether the
// profile runs systemd or s6.
const applyNetwork = `#!/bin/sh
# Generated by nosaic. Applies /etc/nosaic/network.conf.
#
# Missing interfaces are WAITED FOR, then reported and skipped.
#
# Front-panel ports do not exist until the datapath daemon has created them,
# and on this hardware that is minutes after boot, not milliseconds -- the SDK
# has a chip to initialise first. This script used to make one pass and skip
# whatever was absent, which meant every front-panel address in the file was
# silently never applied on a normal boot. The switch came up with a
# management address, no routed ports, and nothing saying so; the addresses
# had to be typed in by hand every time, and OSPF could not form an adjacency
# because no interface it was configured for had an address.
#
# So: retry until every named interface exists, or until the deadline. A
# management-plane boot with no datapath still finishes -- it just takes the
# deadline to admit it, and says which ports never appeared.

# The switch's own configuration wins over the image's.
#
# /etc/nosaic/network.conf ships in the image and is the same on every switch
# built from it. /mnt/data/config/network.conf belongs to THIS switch and
# survives an image being replaced, which is what makes changing an address
# something other than a rebuild.
CONF=/etc/nosaic/network.conf
[ -r /mnt/data/config/network.conf ] && CONF=/mnt/data/config/network.conf
[ -r "$CONF" ] || exit 0

# How long to wait for the datapath to create its interfaces.
WAIT_SECS=${NOSAIC_NET_WAIT:-600}
POLL_SECS=5

say() { echo "NOSAIC-NET $*"; }

say "using $CONF"

# Forwarding on. This is a router; a router that does not forward is the most
# confusing possible state, because every interface is up, every route is
# present, every neighbour is reachable from the box itself, and traffic that
# arrives to be forwarded is silently discarded.
#
# Nothing else in the image sets it, and the default is off. EdgeNOS shipped the
# same board with it unset and measured the result: ForwDatagrams=0 against
# InAddrErrors=47341 -- forty-seven thousand packets accepted and dropped.
#
# Both families, because a box that routes IPv4 and drops IPv6 is a worse fault
# than one that routes neither: half the traffic works.
for f in /proc/sys/net/ipv4/ip_forward /proc/sys/net/ipv6/conf/all/forwarding; do
    if [ -w "$f" ]; then
        echo 1 > "$f" && say "forwarding on ($f)"
    fi
done

# Interfaces first: a route cannot be installed through a device that has no
# address, and the error if you try names neither.
apply_ifaces() {
missing=0
while read -r kind name rest; do
    case "$kind" in
        iface) ;;
        *) continue ;;
    esac
    addr=$(echo "$rest" | awk '{print $1}')
    mtu=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="mtu") print $(i+1)}')
    mac=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="mac") print $(i+1)}')

    if ! ip link show "$name" >/dev/null 2>&1; then
        missing=$((missing + 1))
        echo "$name" >> "$ABSENT"
        continue
    fi

    # Already correct? Then touch nothing.
    #
    # This is not an optimisation, it is the whole safety of retrying. The
    # block below takes an interface DOWN to set its MAC, and this loop runs
    # every few seconds until the datapath has created its ports -- which is
    # minutes. Without this test the management interface was carried down and
    # up over a hundred times per boot, and came back NO-CARRIER and stayed
    # there: the box lost its management network for the entire wait and did
    # not get it back. Re-running this script must be free for anything
    # already in the state the file asks for.
    have_addr=$(ip -o addr show dev "$name" 2>/dev/null | grep -c "${addr%%/*}/")
    have_mac=$(cat /sys/class/net/"$name"/address 2>/dev/null)
    is_up=$(ip link show "$name" 2>/dev/null | head -1 | grep -c "[<,]UP[,>]")
    if [ "$have_addr" -ge 1 ] && [ "$is_up" -ge 1 ] &&
       { [ -z "$mac" ] || [ "$have_mac" = "$mac" ]; }; then
        continue
    fi
    # The address, before the interface comes up. A board states one when its
    # hardware does not carry it anywhere the driver can find: on these
    # switches the MAC lives in board data on an i2c SEEPROM, and the driver
    # only probes at all because it falls back to a random address. Leaving
    # that random address in place would mean a switch whose identity changes
    # every boot.
    if [ -n "$mac" ] && [ "$have_mac" != "$mac" ]; then
        ip link set dev "$name" down 2>/dev/null
        if ip link set dev "$name" address "$mac" 2>/dev/null; then
            say "$name mac $mac"
        else
            say "$name FAILED to set mac $mac"
        fi
    fi
    [ -n "$mtu" ] && ip link set dev "$name" mtu "$mtu" 2>/dev/null
    ip link set dev "$name" up 2>/dev/null
    if ip addr add "$addr" dev "$name" 2>/dev/null; then
        say "$name $addr${mtu:+ mtu $mtu}"
    else
        # Already present is the common case on a re-run, and is not a problem.
        ip addr show dev "$name" | grep -q "${addr%%/*}" \
            && say "$name $addr already set" \
            || say "$name FAILED to set $addr"
    fi
done < "$CONF"
return $missing
}

apply_routes() {
while read -r kind dest via gw rest; do
    [ "$kind" = "route" ] || continue
    [ "$via" = "via" ] || continue
    # Present already? Match the destination, and only the destination.
    #
    # This used to also accept "^default via ${gw}", which makes every other
    # route through the same gateway look like it is already installed. The
    # management pin -- 10.22.1.0/24 via the same router as the default route --
    # was skipped every boot for that reason, and the switch went back to
    # carrying its own management traffic across the datapath. A route named
    # "default" prints as "default via ..." anyway, so the extra alternative
    # was never needed for the case it was presumably written for.
    ip route show | grep -q "^${dest} via ${gw}" && continue
    if ip route add "$dest" via "$gw" $rest 2>/dev/null; then
        say "route $dest via $gw"
    fi
done < "$CONF"
}

ABSENT=$(mktemp 2>/dev/null || echo /tmp/nosaic-net-absent)
deadline=$(( $(date +%s) + WAIT_SECS ))
announced=""
routed=0
while : ; do
    : > "$ABSENT"
    apply_ifaces
    missing=$?
    # After the first pass, whatever exists is configured -- so put its routes
    # in now rather than at the end. Otherwise a board still waiting for
    # front-panel ports has no default route, and is unreachable for the whole
    # timeout: exactly when someone wants to log in and find out why the ports
    # are missing.
    if [ "$routed" -eq 0 ]; then
        apply_routes
        routed=1
    fi
    [ "$missing" -eq 0 ] && break
    now=$(date +%s)
    [ "$now" -ge "$deadline" ] && break
    waiting=$(tr "\n" " " < "$ABSENT")
    if [ "$waiting" != "$announced" ]; then
        say "waiting for: $waiting"
        announced="$waiting"
    fi
    sleep "$POLL_SECS"
done
ABSENT_FINAL="$ABSENT"

# Once now and once at the end. The first pass is what makes the box reachable
# while the wait above is still running: a route whose gateway is already on a
# configured interface works immediately, and holding it back until every
# interface in the file has appeared means no management for the whole timeout
# -- which is exactly the situation where someone wants to log in and find out
# why. Front-panel ports create their routes on the second pass.
apply_routes

if [ -s "$ABSENT_FINAL" ]; then
    say "never appeared after ${WAIT_SECS}s: $(tr "\n" " " < "$ABSENT_FINAL")"
fi
rm -f "$ABSENT_FINAL"

apply_routes

say done
`

func writeNetwork(o Options, rootfs string) (bool, error) {
	src := filepath.Join(o.Root, "platform", o.Board.ID, "config", "network.conf")
	b, err := os.ReadFile(src)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if err := writeFile(rootfs, "/etc/nosaic/network.conf", string(b), 0o644); err != nil {
		return false, err
	}
	if err := writeFile(rootfs, "/etc/nosaic/apply-network.sh", applyNetwork, 0o755); err != nil {
		return false, err
	}
	fmt.Fprintf(o.Log, "    network configuration from the board\n")
	return true, nil
}

// bindASICIRQ binds the switch chip to uio_pci_generic so the datapath can take
// interrupts instead of polling for them.
//
// The vendor and device ids are read off the device rather than written down: a
// board that states its ASIC's PCI address has already said which device this
// is, and saying it twice is how the two come to disagree.
//
// It exits 0 whatever happens. A board whose chip cannot be bound should still
// boot -- the datapath will fail attach and say why, which is a better failure
// than an init system that refuses to bring anything up.
const bindASICIRQ = `#!/bin/sh
# Generated by nosaic.
D=/sys/bus/pci/devices/@ASIC_PCI@
DRV=/sys/bus/pci/drivers/uio_pci_generic

say() { echo "NOSAIC-IRQ $*"; }

[ -d "$D" ]   || { say "@ASIC_PCI@ is not on the bus"; exit 0; }
[ -d "$DRV" ] || { say "no uio_pci_generic in this kernel"; exit 0; }
[ -e "$D/driver" ] && { say "@ASIC_PCI@ already bound"; exit 0; }

V=$(cut -c3- "$D/vendor")
P=$(cut -c3- "$D/device")
if echo "$V $P" > "$DRV/new_id" 2>/dev/null && [ -e "$D/driver" ]; then
    say "@ASIC_PCI@ bound to uio_pci_generic ($V:$P)"
else
    # The usual cause is a device that does not support INTx masking, which
    # uio_pci_generic requires and refuses without.
    say "could not bind @ASIC_PCI@ ($V:$P); the datapath will have to poll"
fi
exit 0
`

// writeBoardFRR installs the board's routing configuration, if it has one.
//
// The FRR package ships a default frr.conf identical on every switch built
// from the image; a board that has its own routing to do replaces it here, the
// same way it replaces the addressing with network.conf. Without this a board
// could record its OSPF configuration in its own directory and have it reach
// nothing, which is worse than not recording it.
//
// Ownership is the part that bites: frr.conf is 0640 and the daemons run as
// frr, so a file landing root-owned is a daemon that starts, reads nothing,
// and reports that OSPF is not enabled. The ids come from the recipe's own
// users: declaration.
func writeBoardFRR(o Options, rootfs string) (bool, error) {
	src := filepath.Join(o.Root, "platform", o.Board.ID, "config", "frr.conf")
	b, err := os.ReadFile(src)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if err := writeFile(rootfs, "/etc/frr/frr.conf", string(b), 0o640); err != nil {
		return false, err
	}
	if err := os.Chown(filepath.Join(rootfs, "etc/frr/frr.conf"), frrUID, frrGID); err != nil {
		return false, fmt.Errorf("frr.conf ownership: %w", err)
	}
	fmt.Fprintf(o.Log, "    routing configuration from the board\n")
	return true, nil
}

// The frr account, from recipes/frr/recipe.yml.
const (
	frrUID = 101
	frrGID = 101
)
