package imgbuild

import (
	"fmt"
	"os"
	"path/filepath"
)

// writeNetwork installs the board's network configuration and the service that
// applies it.
//
// Until this existed an image booted with no addresses at all: iproute2 was in
// the profile and nothing ever called it. A switch that reaches a login and
// cannot be reached over the network is only half a switch, and on a box whose
// console is a serial cable in another building that difference matters.
//
// The configuration is the board's, not the image's, because addresses are a
// property of where the box is plugged in. It is applied by a generated
// service like everything else, so the same declaration works whether the
// profile runs systemd or s6.
const applyNetwork = `#!/bin/sh
# Generated by nosaic. Applies /etc/nosaic/network.conf.
#
# Missing interfaces are WAITED FOR, then reported and skipped.
#
# Front-panel ports do not exist until the datapath daemon has created them,
# and on this hardware that is minutes after boot, not milliseconds -- the SDK
# has a chip to initialise first. This script used to make one pass and skip
# whatever was absent, which meant every front-panel address in the file was
# silently never applied on a normal boot. The switch came up with a
# management address, no routed ports, and nothing saying so; the addresses
# had to be typed in by hand every time, and OSPF could not form an adjacency
# because no interface it was configured for had an address.
#
# So: retry until every named interface exists, or until the deadline. A
# management-plane boot with no datapath still finishes -- it just takes the
# deadline to admit it, and says which ports never appeared.

# The switch's own configuration wins over the image's.
#
# /etc/nosaic/network.conf ships in the image and is the same on every switch
# built from it. /mnt/data/config/network.conf belongs to THIS switch and
# survives an image being replaced, which is what makes changing an address
# something other than a rebuild.
CONF=/etc/nosaic/network.conf
[ -r /mnt/data/config/network.conf ] && CONF=/mnt/data/config/network.conf
# A test names its own file; nothing on a switch sets this.
[ -n "$NOSAIC_NET_CONF" ] && CONF=$NOSAIC_NET_CONF
[ -r "$CONF" ] || exit 0

# How long to wait for the datapath to create its interfaces.
# ⚠ LONG ENOUGH FOR THE SLOWEST DATAPATH, NOT FOR A TYPICAL ONE.
#
# This waits for interfaces the datapath creates, so the ceiling has to clear
# however long that takes. On a board with 48 external PHYs it takes about
# eleven minutes: Broadcom's driver downloads firmware to every one of them
# over MDIO -- 1.8 million register writes -- before the chip reports its
# ports. At the old ten-minute ceiling that board configured eth0, gave up on
# the rest, and came up with no transit addressing at all, which reads as a
# dead data plane rather than as a timeout.
#
# Nothing is lost by the higher ceiling: a board whose interfaces appear in
# seconds stops waiting the moment they do.
WAIT_SECS=${NOSAIC_NET_WAIT:-1500}
POLL_SECS=5

# Reconcile, because the interfaces this configures are destroyed and recreated
# underneath it.
#
# The taps belong to the datapath daemon. When it restarts -- and it is
# supervised with restart:always, so it restarts on its own after a crash --
# every tap is destroyed and recreated BARE. The loopback's own address goes
# with them. Configuring once at boot therefore leaves a switch that has
# addresses only until the first time the daemon exits, and an operator sees a
# box that boots correctly and later routes nothing, with no event to point at.
#
# So the answer is a timer rather than an event: ask what the state IS and put
# back whatever is missing. That is the same conclusion the 7050TX-64's
# hotplug work reached about ports -- level-triggered, not edge-triggered,
# because the event can be missed entirely and the state cannot.
#
# Re-running is free by construction. apply_ifaces() skips anything already in
# the state the file asks for -- that test is load-bearing and documented
# below -- and apply_routes() skips a route already installed, so a pass with
# nothing to do prints nothing and touches nothing.
#
# Unset means converge once and exit, which is what the boot-time oneshot
# wants. A number means keep going, that many seconds apart.
RECONCILE_SECS=${NOSAIC_NET_RECONCILE:-0}

say() {
    # A second argument of "quiet" drops the line: the VLAN pass runs every
    # few seconds while the datapath starts, and its ports not existing yet
    # is the expected state, not news.
    [ "${2:-}" = quiet ] && return 0
    echo "NOSAIC-NET $1"
}

say "using $CONF"

# Forwarding on. This is a router; a router that does not forward is the most
# confusing possible state, because every interface is up, every route is
# present, every neighbour is reachable from the box itself, and traffic that
# arrives to be forwarded is silently discarded.
#
# Nothing else in the image sets it, and the default is off. EdgeNOS shipped the
# same board with it unset and measured the result: ForwDatagrams=0 against
# InAddrErrors=47341 -- forty-seven thousand packets accepted and dropped.
#
# Both families, because a box that routes IPv4 and drops IPv6 is a worse fault
# than one that routes neither: half the traffic works.
for f in /proc/sys/net/ipv4/ip_forward /proc/sys/net/ipv6/conf/all/forwarding; do
    if [ -w "$f" ]; then
        echo 1 > "$f" && say "forwarding on ($f)"
    fi
done

# VRFs, before the interfaces that belong to them.
#
#     vrf mgmt table 1001
#
# The management port has to be out of the main table. The main table is what
# the datapath mirrors into the chip, and it is what the kernel consults for a
# packet that transits the box. With eth0 in it, a packet that missed in the
# ASIC and was punted could be routed out of the management port, and the
# management network's routes had to be "pinned" into the front-panel routing
# table by hand. A VRF gives the management port a table of its own. It is the
# same answer Cisco (vrf management) and Cumulus (vrf mgmt) reached.
#
# The table number is the operator's, not a name: busybox's ip has no
# "vrf NAME" route keyword, so every route line below is translated to
# "table N" through this line.
vrf_table() {
    awk -v v="$1" '$1=="vrf" && $2==v && $3=="table" {print $4; exit}' "$CONF"
}

apply_vrfs() {
while read -r kind name tbl id rest; do
    [ "$kind" = "vrf" ] || continue
    if [ "$tbl" != "table" ] || [ -z "$id" ]; then
        say "vrf $name: expected 'vrf $name table <N>'"
        continue
    fi
    if ! ip link show "$name" >/dev/null 2>&1; then
        if ip link add "$name" type vrf table "$id" 2>/dev/null; then
            say "vrf $name table $id"
        else
            # The usual cause is a kernel without CONFIG_NET_VRF. That kernel
            # is outside the A/B slot, so an image upgrade does not bring it.
            say "vrf $name table $id FAILED"
            continue
        fi
    fi
    ip link show "$name" 2>/dev/null | head -1 | grep -q "[<,]UP[,>]" \
        || ip link set dev "$name" up 2>/dev/null
done < "$CONF"

# Services listen in the default VRF, and a connection arriving on a VRF
# member does not reach them without this: sshd would answer on the front
# panel and not on the management port, which is the wrong way round.
# Binding each service to the VRF would be the alternative, and dropbear has no
# option for it, and busybox has no "ip vrf exec".
if grep -q '^vrf ' "$CONF"; then
    for f in /proc/sys/net/ipv4/tcp_l3mdev_accept /proc/sys/net/ipv4/udp_l3mdev_accept; do
        [ -w "$f" ] && [ "$(cat "$f")" != 1 ] && echo 1 > "$f" && say "$(basename "$f") on"
    done
fi
}

# VLANs, switch ports and routed VLAN interfaces, before the addresses.
#
#     lag po1 lacp swp49,swp50
#     vlan 10
#     switchport swp1 access 10
#     switchport swp49 trunk 10,20 native 1
#     iface vlan10 10.0.10.1/24
#
# Each line is handed to the CLI, which talks to the datapath, so the same
# file does the same thing on a chip and on the virtual board. switchport
# states a port's whole membership, and an iface on vlan<N> brings its SVI
# into being first -- vlan<N> does not exist until the datapath makes it, and
# the address loop below would otherwise wait for it for ever.
#
# Every one of them is safe to repeat, which is what lets this run on the
# reconcile timer: a datapath restart forgets every VLAN, and the next pass
# puts them back the way it puts back addresses.
#
# Like addresses, a line taken OUT of the file is not undone on the switch:
# "nosaic vlan del", "switchport <port> none" or "svi del" does that.
#
# $1 = "quiet" while waiting for the datapath, whose ports do not exist yet.
apply_vlans() {
command -v nosaic >/dev/null 2>&1 || return 0
grep -Eq '^(vlan|switchport|lag)[[:space:]]|^iface[[:space:]]+vlan[0-9]' "$CONF" || return 0
# LAGs first, in a pass of their own: a switchport or iface line may name one,
# and it has to exist before it can be put in a VLAN or given an address.
while read -r kind a mode ports; do
    [ "$kind" = "lag" ] && [ -n "$a" ] || continue
    out=$(nosaic lag "$a" "$mode" $ports 2>&1) || say "lag $a $mode $ports FAILED: $out" "$1"
done < "$CONF"
while read -r kind a rest; do
    out=""
    case "$kind" in
        vlan)
            [ -n "$a" ] || continue
            out=$(nosaic vlan add "$a" 2>&1) || say "vlan $a FAILED: $out" "$1"
            ;;
        switchport)
            [ -n "$a" ] || continue
            # shellcheck disable=SC2086 -- rest is the membership, word-split on purpose
            out=$(nosaic switchport "$a" $rest 2>&1) || say "switchport $a $rest FAILED: $out" "$1"
            ;;
        iface)
            case "$a" in
                vlan[0-9]*)
                    out=$(nosaic svi add "${a#vlan}" 2>&1) || say "svi $a FAILED: $out" "$1"
                    ;;
            esac
            ;;
    esac
done < "$CONF"
}

# Interfaces first: a route cannot be installed through a device that has no
# address, and the error if you try names neither.
apply_ifaces() {
missing=0
while read -r kind name rest; do
    case "$kind" in
        iface) ;;
        *) continue ;;
    esac
    addr=$(echo "$rest" | awk '{print $1}')
    mtu=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="mtu") print $(i+1)}')
    mac=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="mac") print $(i+1)}')
    vrf=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="vrf") print $(i+1)}')

    # "mac auto" means ask the board, and it is what makes an image generic.
    #
    # A management NIC whose own EEPROM was never programmed comes up with a
    # vendor OUI and an all-zero suffix, so every unit of that model presents
    # the SAME address. Writing the right one into this file fixes one switch
    # and makes the image wrong for every other: the next unit built from it
    # then presents the first one's identity. The board's identity PROM knows
    # its own allocated block, so "auto" reads it from there.
    #
    # Resolved once per pass rather than cached: this script is retried until
    # the datapath's ports exist, and on an early pass the i2c device may not
    # be instantiated yet. Failing quietly and trying again next pass is
    # right; the interface keeps whatever it has until the answer arrives.
    if [ "$mac" = "auto" ]; then
        mac=$(nosaic platform mac 2>/dev/null) || mac=""
        [ -z "$mac" ] && say "$name mac auto: the board cannot say yet"
    fi

    if ! ip link show "$name" >/dev/null 2>&1; then
        missing=$((missing + 1))
        echo "$name" >> "$ABSENT"
        continue
    fi

    # Already correct? Then touch nothing.
    #
    # This is not an optimisation, it is the whole safety of retrying. The
    # block below takes an interface DOWN to set its MAC, and this loop runs
    # every few seconds until the datapath has created its ports -- which is
    # minutes. Without this test the management interface was carried down and
    # up over a hundred times per boot, and came back NO-CARRIER and stayed
    # there: the box lost its management network for the entire wait and did
    # not get it back. Re-running this script must be free for anything
    # already in the state the file asks for.
    have_addr=$(ip -o addr show dev "$name" 2>/dev/null | grep -c "${addr%%/*}/")
    have_mac=$(cat /sys/class/net/"$name"/address 2>/dev/null)
    is_up=$(ip link show "$name" 2>/dev/null | head -1 | grep -c "[<,]UP[,>]")
    have_vrf=$(ip -o link show "$name" 2>/dev/null | awk '{for(i=1;i<NF;i++) if($i=="master") print $(i+1)}')
    if [ "$have_addr" -ge 1 ] && [ "$is_up" -ge 1 ] &&
       { [ -z "$mac" ] || [ "$have_mac" = "$mac" ]; } &&
       { [ -z "$vrf" ] || [ "$have_vrf" = "$vrf" ]; }; then
        continue
    fi
    # Into the VRF before anything else, and only when it is not there already.
    #
    # Enslaving cycles the interface down and up, which the kernel does to
    # flush its routes and neighbours -- and a static IPv6 address does not
    # survive the down. So this goes before the addresses, and it is guarded
    # by the same "already correct" rule as the MAC below: a pass that
    # re-enslaved every time would flap the management port every few seconds.
    if [ -n "$vrf" ] && [ "$have_vrf" != "$vrf" ]; then
        if ip link set dev "$name" master "$vrf" 2>/dev/null; then
            say "$name vrf $vrf"
        else
            say "$name FAILED to join vrf $vrf"
        fi
    fi
    # The address, before the interface comes up. A board states one when its
    # hardware does not carry it anywhere the driver can find: on these
    # switches the MAC lives in board data on an i2c SEEPROM, and the driver
    # only probes at all because it falls back to a random address. Leaving
    # that random address in place would mean a switch whose identity changes
    # every boot.
    if [ -n "$mac" ] && [ "$have_mac" != "$mac" ]; then
        ip link set dev "$name" down 2>/dev/null
        if ip link set dev "$name" address "$mac" 2>/dev/null; then
            say "$name mac $mac"
        else
            say "$name FAILED to set mac $mac"
        fi
    fi
    [ -n "$mtu" ] && ip link set dev "$name" mtu "$mtu" 2>/dev/null
    ip link set dev "$name" up 2>/dev/null
    if ip addr add "$addr" dev "$name" 2>/dev/null; then
        say "$name $addr${mtu:+ mtu $mtu}"
    else
        # Already present is the common case on a re-run, and is not a problem.
        ip addr show dev "$name" | grep -q "${addr%%/*}" \
            && say "$name $addr already set" \
            || say "$name FAILED to set $addr"
    fi
done < "$CONF"
return $missing
}

apply_routes() {
while read -r kind dest via gw rest; do
    [ "$kind" = "route" ] || continue
    [ "$via" = "via" ] || continue
    # Present already? Match the destination, and only the destination.
    #
    # This used to also accept "^default via ${gw}", which makes every other
    # route through the same gateway look like it is already installed. The
    # management pin -- 10.22.1.0/24 via the same router as the default route --
    # was skipped every boot for that reason, and the switch went back to
    # carrying its own management traffic across the datapath. A route named
    # "default" prints as "default via ..." anyway, so the extra alternative
    # was never needed for the case it was presumably written for.
    #
    # The family comes from the gateway, not from a flag in the file. Plain
    # "ip route" assumes inet, so an IPv6 gateway was rejected with
    # "inet address is expected" -- and rejected silently, because the failure
    # is swallowed below. A config format that accepts IPv6 interfaces and not
    # IPv6 routes is a trap: it takes the line, says nothing, and leaves the
    # box with addresses and no way off the subnet.
    case "$gw" in
        *:*) fam="-6" ;;
        *)   fam="" ;;
    esac
    # "vrf NAME" becomes "table N". Everything else on the line is ip's.
    vrf=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="vrf") print $(i+1)}')
    table=""
    if [ -n "$vrf" ]; then
        rest=$(echo "$rest" | awk '{s=""; for(i=1;i<=NF;i++) if($i=="vrf") i++; else s=s" "$i; print s}')
        table=$(vrf_table "$vrf")
        if [ -z "$table" ]; then
            say "route $dest via $gw: no 'vrf $vrf table <N>' line"
            continue
        fi
        table="table $table"
    fi
    ip $fam route show $table | grep -q "^${dest} via ${gw}" && continue
    if ip $fam route add "$dest" via "$gw" $rest $table 2>/dev/null; then
        say "route $dest via $gw${vrf:+ vrf $vrf}"
    else
        # Worth saying out loud. The common cause is a gateway that is not on
        # any configured subnet, and a silent failure there is a box that comes
        # up looking correct and is reachable from nowhere.
        ip $fam route show $table | grep -q "^${dest} " \
            || say "route $dest via $gw${vrf:+ vrf $vrf} FAILED"
    fi
done < "$CONF"
}

ABSENT=$(mktemp 2>/dev/null || echo /tmp/nosaic-net-absent)
deadline=$(( $(date +%s) + WAIT_SECS ))
announced=""
routed=0
while : ; do
    : > "$ABSENT"
    apply_vrfs
    apply_vlans quiet
    apply_ifaces
    missing=$?
    # After the first pass, whatever exists is configured -- so put its routes
    # in now rather than at the end. Otherwise a board still waiting for
    # front-panel ports has no default route, and is unreachable for the whole
    # timeout: exactly when someone wants to log in and find out why the ports
    # are missing.
    if [ "$routed" -eq 0 ]; then
        apply_routes
        routed=1
    fi
    [ "$missing" -eq 0 ] && break
    now=$(date +%s)
    [ "$now" -ge "$deadline" ] && break
    waiting=$(tr "\n" " " < "$ABSENT")
    if [ "$waiting" != "$announced" ]; then
        say "waiting for: $waiting"
        announced="$waiting"
    fi
    sleep "$POLL_SECS"
done
ABSENT_FINAL="$ABSENT"

# Once now and once at the end. The first pass is what makes the box reachable
# while the wait above is still running: a route whose gateway is already on a
# configured interface works immediately, and holding it back until every
# interface in the file has appeared means no management for the whole timeout
# -- which is exactly the situation where someone wants to log in and find out
# why. Front-panel ports create their routes on the second pass.
apply_routes

# Once more, out loud: whatever still fails now is worth a line.
apply_vlans
apply_ifaces >/dev/null 2>&1 || :

if [ -s "$ABSENT_FINAL" ]; then
    say "never appeared after ${WAIT_SECS}s: $(tr "\n" " " < "$ABSENT_FINAL")"
fi
rm -f "$ABSENT_FINAL"

apply_routes

say done

if [ "$RECONCILE_SECS" -gt 0 ] 2>/dev/null; then
    say "reconciling every ${RECONCILE_SECS}s"
    while : ; do
        sleep "$RECONCILE_SECS"
        # NOT silenced. A pass with nothing to do already prints nothing,
        # so anything this says is an address or a route that had gone --
        # which is the one thing an operator needs to see in the log.
        apply_vrfs
        apply_vlans
        apply_ifaces || :
        apply_routes
    done
fi
`

func writeNetwork(o Options, rootfs string) (bool, error) {
	/*
	 * ⚠ THE SCRIPT ALWAYS SHIPS. THE CONFIG IS OPTIONAL.
	 *
	 * These used to be installed together, so a board that shipped no
	 * config/network.conf got no apply-network.sh either -- and the caller
	 * then skipped the service as well. The effect was that taking one lab
	 * switch's addresses OUT of the image took addressing out of every
	 * switch built from it, with no message anywhere: the script that would
	 * have said "no network configuration" was the thing not installed.
	 * The box came up on the console with a random tg3 MAC and no route in.
	 *
	 * A switch's own addresses belong in /mnt/data/config/network.conf,
	 * which the script prefers and which survives an upgrade. So the script
	 * is what makes a generic image usable, and it has to be there whether
	 * or not the board model ships defaults of its own.
	 */
	if err := writeFile(rootfs, "/etc/nosaic/apply-network.sh", applyNetwork, 0o755); err != nil {
		return false, err
	}

	src := filepath.Join(o.Root, "platform", o.Board.ID, "config", "network.conf")
	b, err := os.ReadFile(src)
	if os.IsNotExist(err) {
		fmt.Fprintf(o.Log, "    no board network configuration; this image expects\n")
		fmt.Fprintf(o.Log, "    /mnt/data/config/network.conf on the switch itself\n")
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if err := writeFile(rootfs, "/etc/nosaic/network.conf", string(b), 0o644); err != nil {
		return false, err
	}
	fmt.Fprintf(o.Log, "    network configuration from the board\n")
	return true, nil
}

// bindASICIRQ binds the switch chip to uio_pci_generic so the datapath can take
// interrupts instead of polling for them.
//
// The vendor and device ids are read off the device rather than written down: a
// board that states its ASIC's PCI address has already said which device this
// is, and saying it twice is how the two come to disagree.
//
// It exits 0 whatever happens. A board whose chip cannot be bound should still
// boot -- the datapath will fail attach and say why, which is a better failure
// than an init system that refuses to bring anything up.
const bindASICIRQ = `#!/bin/sh
# Generated by nosaic.
D=/sys/bus/pci/devices/@ASIC_PCI@
DRV=/sys/bus/pci/drivers/uio_pci_generic

say() { echo "NOSAIC-IRQ $*"; }

[ -d "$D" ]   || { say "@ASIC_PCI@ is not on the bus"; exit 0; }
[ -d "$DRV" ] || { say "no uio_pci_generic in this kernel"; exit 0; }
[ -e "$D/driver" ] && { say "@ASIC_PCI@ already bound"; exit 0; }

V=$(cut -c3- "$D/vendor")
P=$(cut -c3- "$D/device")
if echo "$V $P" > "$DRV/new_id" 2>/dev/null && [ -e "$D/driver" ]; then
    say "@ASIC_PCI@ bound to uio_pci_generic ($V:$P)"
else
    # The usual cause is a device that does not support INTx masking, which
    # uio_pci_generic requires and refuses without.
    say "could not bind @ASIC_PCI@ ($V:$P); the datapath will have to poll"
fi
exit 0
`

// writeBoardFRR installs the board's routing configuration, if it has one.
//
// The FRR package ships a default frr.conf identical on every switch built
// from the image; a board that has its own routing to do replaces it here, the
// same way it replaces the addressing with network.conf. Without this a board
// could record its OSPF configuration in its own directory and have it reach
// nothing, which is worse than not recording it.
//
// Ownership is the part that bites: frr.conf is 0640 and the daemons run as
// frr, so a file landing root-owned is a daemon that starts, reads nothing,
// and reports that OSPF is not enabled. The ids come from the recipe's own
// users: declaration.
func writeBoardFRR(o Options, rootfs string) (bool, error) {
	src := filepath.Join(o.Root, "platform", o.Board.ID, "config", "frr.conf")
	b, err := os.ReadFile(src)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if err := writeFile(rootfs, "/etc/frr/frr.conf", string(b), 0o640); err != nil {
		return false, err
	}
	if err := os.Chown(filepath.Join(rootfs, "etc/frr/frr.conf"), frrUID, frrGID); err != nil {
		return false, fmt.Errorf("frr.conf ownership: %w", err)
	}
	fmt.Fprintf(o.Log, "    routing configuration from the board\n")
	return true, nil
}

// The frr account, from recipes/frr/recipe.yml.
const (
	frrUID = 101
	frrGID = 101
)
