package imgbuild

import (
	"fmt"
	"os"
	"path/filepath"
)

// writeNetwork installs the board's network configuration and the service that
// applies it.
//
// Until this existed an image booted with no addresses at all: iproute2 was in
// the profile and nothing ever called it. A switch that reaches a login and
// cannot be reached over the network is only half a switch, and on a box whose
// console is a serial cable in another building that difference matters.
//
// The configuration is the board's, not the image's, because addresses are a
// property of where the box is plugged in. It is applied by a generated
// service like everything else, so the same declaration works whether the
// profile runs systemd or s6.
const applyNetwork = `#!/bin/sh
# Generated by nosaic. Applies /etc/nosaic/network.conf.
#
# Missing interfaces are reported and skipped rather than treated as failure.
# Front-panel ports do not exist until the datapath daemon has created them, so
# on a management-plane boot most of this file names things that are not there
# yet -- which is expected, and not a fault to fail the boot over.

CONF=/etc/nosaic/network.conf
[ -r "$CONF" ] || exit 0

say() { echo "NOSAIC-NET $*"; }

# Interfaces first: a route cannot be installed through a device that has no
# address, and the error if you try names neither.
while read -r kind name rest; do
    case "$kind" in
        iface) ;;
        *) continue ;;
    esac
    addr=$(echo "$rest" | awk '{print $1}')
    mtu=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="mtu") print $(i+1)}')
    mac=$(echo "$rest" | awk '{for(i=1;i<=NF;i++) if($i=="mac") print $(i+1)}')

    if ! ip link show "$name" >/dev/null 2>&1; then
        say "$name absent, skipped (no datapath yet?)"
        continue
    fi
    # The address, before the interface comes up. A board states one when its
    # hardware does not carry it anywhere the driver can find: on these
    # switches the MAC lives in board data on an i2c SEEPROM, and the driver
    # only probes at all because it falls back to a random address. Leaving
    # that random address in place would mean a switch whose identity changes
    # every boot.
    if [ -n "$mac" ]; then
        ip link set dev "$name" down 2>/dev/null
        if ip link set dev "$name" address "$mac" 2>/dev/null; then
            say "$name mac $mac"
        else
            say "$name FAILED to set mac $mac"
        fi
    fi
    [ -n "$mtu" ] && ip link set dev "$name" mtu "$mtu" 2>/dev/null
    ip link set dev "$name" up 2>/dev/null
    if ip addr add "$addr" dev "$name" 2>/dev/null; then
        say "$name $addr${mtu:+ mtu $mtu}"
    else
        # Already present is the common case on a re-run, and is not a problem.
        ip addr show dev "$name" | grep -q "${addr%%/*}" \
            && say "$name $addr already set" \
            || say "$name FAILED to set $addr"
    fi
done < "$CONF"

while read -r kind dest via gw rest; do
    [ "$kind" = "route" ] || continue
    [ "$via" = "via" ] || continue
    if ip route add "$dest" via "$gw" $rest 2>/dev/null; then
        say "route $dest via $gw"
    else
        ip route show | grep -q "$gw" \
            && say "route $dest via $gw already present" \
            || say "route $dest via $gw FAILED (is the gateway reachable?)"
    fi
done < "$CONF"

say done
`

func writeNetwork(o Options, rootfs string) (bool, error) {
	src := filepath.Join(o.Root, "platform", o.Board.ID, "config", "network.conf")
	b, err := os.ReadFile(src)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if err := writeFile(rootfs, "/etc/nosaic/network.conf", string(b), 0o644); err != nil {
		return false, err
	}
	if err := writeFile(rootfs, "/etc/nosaic/apply-network.sh", applyNetwork, 0o755); err != nil {
		return false, err
	}
	fmt.Fprintf(o.Log, "    network configuration from the board\n")
	return true, nil
}
