package imgbuild

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"syscall"
)

// writePrivilege configures how the login account becomes root, and refuses to
// build an image where that does not actually work.
//
// The check is the point. base/identity.yml declared `privilege: sudo` from the
// first commit and no profile ever packaged sudo, so every minimal image shipped
// with root locked and no way to elevate at all. Nothing caught it, because a
// declaration in one file and a package list in another cannot disagree unless
// something compares them -- and this is that something.
//
// It surfaced on the first real board, where the platform HAL could not open
// the board controller's PCI resource, which is root-only. A NOS that cannot
// reach its own hardware is not a NOS.
func writePrivilege(rootfs, account, privilege string, log io.Writer) error {
	switch privilege {
	case "doas":
		// One rule: the login account may become root, and must authenticate
		// as itself. persist keeps a short timestamp so a sequence of commands
		// during bring-up is not a sequence of prompts.
		conf := fmt.Sprintf(""+
			"# Generated by nosaic from base/<profile>.yml.\n"+
			"#\n"+
			"# nopass, because the shipped image contains no credential at all:\n"+
			"# %[1]s has an empty password and root is locked, so there is\n"+
			"# nothing for doas to check and `permit persist` fails outright with\n"+
			"# \"Authentication required\". That is not a safer switch, it is one\n"+
			"# with no path to its own hardware -- which is the defect this file\n"+
			"# exists to fix, so it must not be reintroduced here.\n"+
			"#\n"+
			"# The boundary is unchanged: with no password set there is no network\n"+
			"# login and no console login that asks for one, so physical access is\n"+
			"# the whole of it, and physical access already implies control of the\n"+
			"# box. Once a password is set, the console does ask for it, and this\n"+
			"# line should tighten to `permit persist` -- config lives on the data\n"+
			"# partition, so that is a change the switch can make about itself.\n"+
			"permit nopass %[1]s as root\n", account)
		if err := writeFile(rootfs, "/etc/doas.conf", conf, 0o600); err != nil {
			return err
		}
		return verifyPrivBinary(rootfs, "/usr/bin/doas", privilege, log)

	case "sudo":
		// NOPASSWD for the same reason doas gets nopass: the shipped image
		// contains no credential at all, so a rule that demands one cannot be
		// satisfied and the switch has no path to its own hardware. The boot
		// self-test on the systemd tiers is what caught this -- the doas half
		// was fixed on the board and the sudo half was left requiring a
		// password nobody has.
		conf := fmt.Sprintf(""+
			"# Generated by nosaic from base/<profile>.yml.\n"+
			"#\n"+
			"# NOPASSWD because the image ships no credential: %[1]s has an empty\n"+
			"# password and root is locked, so a rule requiring one can never be\n"+
			"# satisfied. With no password set there is no network login and no\n"+
			"# console login that asks for one, so physical access is the whole\n"+
			"# boundary -- and it already implies control of a switch. Once a\n"+
			"# password exists this should drop NOPASSWD; config lives on the data\n"+
			"# partition, so the switch can make that change about itself.\n"+
			"Defaults\t!lecture\n"+
			"root\tALL=(ALL:ALL) ALL\n"+
			"%[1]s\tALL=(ALL:ALL) NOPASSWD: ALL\n", account)
		// sudo refuses to read a sudoers file that anyone but root can write,
		// and reports it as a syntax-looking error.
		if err := writeFile(rootfs, "/etc/sudoers", conf, 0o440); err != nil {
			return err
		}
		return verifyPrivBinary(rootfs, "/usr/bin/sudo", privilege, log)

	case "", "none":
		// Not an error only where a board genuinely wants it, and it is worth
		// saying out loud rather than passing over in silence.
		fmt.Fprintln(log, "  privilege: none — this image has no path to root")
		return nil
	}
	return fmt.Errorf("privilege %q is not one of doas, sudo, none", privilege)
}

// verifyPrivBinary checks that the declared helper is in the image and setuid.
func verifyPrivBinary(rootfs, path, privilege string, log io.Writer) error {
	full := filepath.Join(rootfs, path)
	fi, err := os.Lstat(full)
	if err != nil {
		return fmt.Errorf("this profile declares privilege %q but %s is not in the image: "+
			"add the package that provides it to the profile's packages", privilege, path)
	}
	st, ok := fi.Sys().(*syscall.Stat_t)
	if !ok {
		return fmt.Errorf("cannot read the mode of %s", path)
	}
	mode := st.Mode & 0o7777
	if mode&0o4000 == 0 {
		// A privilege helper that is not setuid runs, fails, and looks like a
		// configuration problem. It is worth failing the build for, because
		// the alternative is finding out on the switch.
		return fmt.Errorf("%s is mode %04o and is not setuid root, so it cannot elevate; "+
			"the recipe that installs it must set mode 4755", path, mode)
	}
	if st.Uid != 0 {
		return fmt.Errorf("%s is setuid to uid %d rather than root", path, st.Uid)
	}
	fmt.Fprintf(log, "  privilege: %s via %s (mode %04o)\n", privilege, path, mode)
	return nil
}
