package imgbuild

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/salvaged-silicon/nosaic-switch/internal/svcgen"
)

// s6Init is /sbin/init on an s6 profile.
//
// s6-svscan must be PID 1, so everything that has to happen before supervision
// starts happens here and then execs it. The service database is compiled at
// boot rather than shipped compiled: the source form is what the image
// contains, it is what an operator can read and edit, and compiling takes
// milliseconds.
const s6Init = `#!/bin/sh
# Generated by nosaic. /sbin/init for the s6 profile.

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Not silenced. An earlier version sent these to /dev/null, and a /proc that
# failed to mount produced no message at all -- the first sign of it was a
# self-test three steps later complaining it could not read /proc/cmdline.
# Nothing during boot gets to fail quietly.
for m in "proc proc /proc" "sysfs sysfs /sys" "devtmpfs devtmpfs /dev"; do
    set -- $m
    # Already-mounted is not a failure: the initramfs moves /dev across rather
    # than leaving it behind, so warning about it would send somebody looking
    # for a fault that is actually correct behaviour.
    if mountpoint -q "$3" 2>/dev/null; then
        continue
    fi
    if ! mount -t "$1" "$2" "$3" ; then
        echo "NOSAIC-S6-WARN could not mount $3"
    fi
done
mkdir -p /dev/pts /run /tmp
mount -t devpts devpts /dev/pts || echo "NOSAIC-S6-WARN could not mount /dev/pts"
mount -t tmpfs  tmpfs  /run     || echo "NOSAIC-S6-WARN could not mount /run"
hostname nosaic || true

echo "NOSAIC-BOOT userspace reached (s6)"

# Only the scan directory. /run/s6-rc belongs to s6-rc-init, which creates it
# as a symlink to the live directory it builds -- pre-creating it as a
# directory makes that fail with "Is a directory", and compiling the database
# into it makes the collision certain.
mkdir -p /run/service

# Compile the service database that svcgen produced. A failure here is worth
# saying out loud: the system will still supervise whatever is in the scan
# directory, but nothing declared will start, and silence would make that look
# like the services simply did not exist.
# Errors go straight to the console, not into a file to be read back.
#
# The first version captured stderr and cat'd it afterwards, and every failure
# printed nothing at all -- which turned three separate faults into one
# indistinguishable symptom. On a switch the console is the only diagnostic
# there is, so anything that can fail during boot says so where it happens.
s6-rc-compile /run/s6-rc-compiled /etc/s6-rc/source
echo "NOSAIC-S6 compile rc=$?"

# s6-svscan has to be PID 1, so the database is brought up from a child that
# waits for the scan directory to go live.
(
    n=0
    while [ ! -p /run/service/.s6-svscan/control ] && [ $n -lt 60 ]; do
        sleep 1
        n=$((n + 1))
    done
    if [ ! -p /run/service/.s6-svscan/control ]; then
        echo "NOSAIC-S6-FAIL the scan directory never went live after ${n}s"
    else
        echo "NOSAIC-S6 scan directory live after ${n}s"
        s6-rc-init -c /run/s6-rc-compiled /run/service
        echo "NOSAIC-S6 init rc=$?"
        s6-rc -u change default
        echo "NOSAIC-S6 change rc=$?"
    fi
    /etc/nosaic/selftest.sh
) &

exec s6-svscan /run/service
`

// writeS6 lays down an s6 profile's init and its service database source.
//
// The service directories are generated by svcgen from the same declaration a
// systemd profile would render into a unit. Until this existed that backend
// had never produced files a running system consumed, which meant it was
// tested but not proven.
// bareName strips a systemd-style suffix, since s6 dependency names have none.
func bareName(n string) string {
	for _, suf := range []string{".service", ".target", ".socket"} {
		if strings.HasSuffix(n, suf) {
			return strings.TrimSuffix(n, suf)
		}
	}
	return n
}

func writeS6(o Options, rootfs string, services ...svcgen.Service) error {
	if err := writeFile(rootfs, "/sbin/init", s6Init, 0o755); err != nil {
		return err
	}

	backend, err := svcgen.For("s6")
	if err != nil {
		return err
	}

	var names []string
	for _, svc := range services {
		files, err := backend.Generate(svc)
		if err != nil {
			return fmt.Errorf("generating %s: %w", svc.Name, err)
		}
		for _, f := range files {
			if err := writeFile(rootfs, f.Path, f.Content, os.FileMode(f.Mode)); err != nil {
				return err
			}
		}
		names = append(names, svc.Name)
	}

	// Satisfy the well-known ordering names.
	//
	// The two init systems differ here in a way a service declaration should
	// not have to know about: systemd resolves "after: network" against an
	// implicit network.target, while s6-rc requires every dependency to be a
	// real service in the database and refuses to compile otherwise. So the
	// names a declaration may reasonably use are realised here as empty
	// oneshots, which is what such a target is in s6-rc terms.
	//
	// Generated from what the services actually reference rather than from a
	// fixed list, so a new ordering name cannot silently break the compile.
	referenced := map[string]bool{}
	defined := map[string]bool{}
	for _, svc := range services {
		defined[svc.Name] = true
		for _, d := range append(append([]string(nil), svc.After...), svc.Wants...) {
			referenced[bareName(d)] = true
		}
	}
	for name := range referenced {
		if defined[name] {
			continue
		}
		dir := "/etc/s6-rc/source/" + name
		if err := writeFile(rootfs, dir+"/type", "oneshot\n", 0o644); err != nil {
			return err
		}
		if err := writeFile(rootfs, dir+"/up", "/bin/true\n", 0o644); err != nil {
			return err
		}
		names = append(names, name)
	}

	// s6-rc brings up a bundle, not a list, so the generated services need one
	// to belong to. "default" is the name s6-rc-init expects by convention.
	base := "/etc/s6-rc/source/default"
	if err := writeFile(rootfs, base+"/type", "bundle\n", 0o644); err != nil {
		return err
	}
	for _, n := range names {
		if err := writeFile(rootfs, filepath.Join(base, "contents.d", n), "", 0o644); err != nil {
			return err
		}
	}
	return nil
}
