package imgbuild

// switchMAC works out this switch's own MAC address before the datapath
// starts, and leaves it in /run/nosaic/base_mac for the datapath to build its
// tap and SVI addresses from.
//
// Every address the datapath hands out -- a routed port's, an SVI's -- is
// derived from one base, and until now that base was a property someone had to
// set by hand on each switch. Where nobody had, every NOSaic switch fell back
// to the same 02:00:00:00:00:xx addresses: on this lab's AS5610 and Nexus the
// tap MACs overlapped index for index with each other's, and two such switches
// on one segment, or two ports of either in one VLAN, collide outright.
//
// The switch knows its own address; it only has to be asked in the right
// place. In order:
//
//  1. the board itself -- "nosaic platform mac", its identity PROM or
//     equivalent, on a board whose HAL can read one;
//  2. the management MAC the switch's own network.conf states for eth0, the
//     same effective file apply-network.sh uses -- on a board whose identity
//     nothing reads yet, that line IS where the switch's identity lives;
//  3. eth0's own address, if it is a real one: not multicast, not locally
//     administered, and not a vendor OUI with an all-zero suffix, which is
//     what an unprogrammed NIC EEPROM presents on every unit of the model.
//
// A tap_mac_base property, where one is set, still wins: it is an operator's
// explicit statement, and this is only the default.
const switchMAC = `#!/bin/sh
# Generated by nosaic. This switch's own MAC, for the datapath's addresses.
# The NOSAIC_ variables are for a test; nothing on a switch sets them.
OUT=${NOSAIC_MAC_OUT:-/run/nosaic/base_mac}
mkdir -p "$(dirname "$OUT")"
rm -f "$OUT"

say() { echo "NOSAIC-MAC $*"; }

# A universally administered unicast address with a real suffix.
usable() {
    case "$1" in
        [0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]:[0-9a-fA-F][0-9a-fA-F]) ;;
        *) return 1 ;;
    esac
    first=$(printf '%d' "0x${1%%:*}")
    [ $((first & 3)) -eq 0 ] || return 1
    case "$1" in
        *:00:00:00) return 1 ;;
    esac
    return 0
}

use() {
    echo "$1" | tr 'A-F' 'a-f' > "$OUT"
    say "$1 (from $2)"
    exit 0
}

m=$(nosaic platform mac 2>/dev/null) && usable "$m" && use "$m" "the board"

CONF=/etc/nosaic/network.conf
[ -r /mnt/data/config/network.conf ] && CONF=/mnt/data/config/network.conf
[ -n "$NOSAIC_NET_CONF" ] && CONF=$NOSAIC_NET_CONF
if [ -r "$CONF" ]; then
    m=$(awk '$1 == "iface" && $2 == "eth0" {
             for (i = 3; i < NF; i++) if ($i == "mac") { print $(i + 1); exit }
         }' "$CONF")
    usable "$m" && use "$m" "eth0's mac in $CONF"
fi

m=$(cat "${NOSAIC_ETH0_ADDR:-/sys/class/net/eth0/address}" 2>/dev/null)
usable "$m" && use "$m" "eth0's own address"

say "no usable address from the board, network.conf or eth0; the datapath's" \
    "addresses fall back to 02:00:00:00:00:xx, the same on every switch"
exit 0
`
