package imgbuild

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/salvaged-silicon/nosaic-switch/internal/svcgen"
)

// writeSystemd sets up systemd as PID 1 for the full and slim profiles.
//
// Before this existed the image builder had exactly two paths, s6 and a
// busybox inittab, and a profile declaring init: systemd fell into the busybox
// one. It produced an image that installed systemd and then never ran it,
// which nothing detected -- the profile validated, the packages built, and the
// box came up on busybox init.
//
// The service declarations are the same ones the s6 path is given. That is the
// point of declaring services abstractly: nothing here is written twice.
func writeSystemd(o Options, rootfs string, services ...svcgen.Service) error {
	// systemd is PID 1 by being /sbin/init, and its own package already ships
	// /usr/sbin/init -> ../lib/systemd/systemd. Leave that alone if it
	// resolves.
	//
	// Writing our own was worse in a way that took two boots to see. An
	// absolute target is correct for the running system but wrong for the
	// initramfs, which tests /mnt/root/sbin/init before switch_root: an
	// absolute link resolves against the initramfs root, so the check fails
	// with "the image has no /sbin/init" on an image whose init is fine. A
	// relative target has to be written relative to where the link physically
	// lands, and after the /usr merge /sbin is itself a symlink, so the
	// obvious "../usr/lib/..." resolves to /usr/usr/lib/... Relative links
	// work in both contexts, which is why systemd ships one.
	initPath := filepath.Join(rootfs, "sbin", "init")
	if _, err := os.Stat(initPath); err != nil {
		if err := os.MkdirAll(filepath.Dir(initPath), 0o755); err != nil {
			return err
		}
		_ = os.Remove(initPath)
		// Relative to the directory the link actually lands in, which is not
		// necessarily the one named above.
		dir, derr := filepath.EvalSymlinks(filepath.Dir(initPath))
		if derr != nil {
			return derr
		}
		target, rerr := filepath.Rel(dir, filepath.Join(rootfs, "usr", "lib", "systemd", "systemd"))
		if rerr != nil {
			return rerr
		}
		if err := os.Symlink(target, initPath); err != nil {
			return fmt.Errorf("/sbin/init: %w", err)
		}
	}

	backend, err := svcgen.For("systemd")
	if err != nil {
		return err
	}

	// A unit is installed but not enabled. Enabling is what systemd's own
	// `systemctl enable` does: a symlink from the target's .wants directory.
	// Doing it here rather than at first boot keeps the image immutable and
	// means a unit cannot fail to start because nothing turned it on.
	wants := filepath.Join(rootfs, "etc", "systemd", "system", "multi-user.target.wants")
	if err := os.MkdirAll(wants, 0o755); err != nil {
		return err
	}
	for _, svc := range services {
		files, err := backend.Generate(svc)
		if err != nil {
			return fmt.Errorf("generating %s: %w", svc.Name, err)
		}
		for _, f := range files {
			if err := writeFile(rootfs, f.Path, f.Content, os.FileMode(f.Mode)); err != nil {
				return err
			}
			name := filepath.Base(f.Path)
			link := filepath.Join(wants, name)
			_ = os.Remove(link)
			if err := os.Symlink("/usr/lib/systemd/system/"+name, link); err != nil {
				return fmt.Errorf("enabling %s: %w", name, err)
			}
		}
	}

	// The marker the boot harness waits for, which every init emits: busybox
	// from inittab, s6 from its stage-1 script, and systemd from here. It is
	// what distinguishes "PID 1 started" from "PID 1 got far enough to run
	// something", and the harness cannot tell those apart without it.
	markerUnit := `# Generated by nosaic.
[Unit]
Description=NOSaic userspace marker
DefaultDependencies=no
After=sysinit.target
Before=multi-user.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/echo "NOSAIC-BOOT userspace reached (systemd)"
StandardOutput=journal+console

[Install]
WantedBy=multi-user.target
`
	if err := writeFile(rootfs, "/usr/lib/systemd/system/nosaic-marker.service",
		markerUnit, 0o644); err != nil {
		return err
	}
	markerLink := filepath.Join(wants, "nosaic-marker.service")
	_ = os.Remove(markerLink)
	if err := os.Symlink("/usr/lib/systemd/system/nosaic-marker.service", markerLink); err != nil {
		return err
	}

	// The self-test the boot harness asserts on, as a unit rather than an
	// inittab line. Ordered after multi-user so it runs once the system it is
	// testing is actually up.
	selftestUnit := `# Generated by nosaic.
[Unit]
Description=NOSaic boot self-test
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/etc/nosaic/selftest.sh
StandardOutput=journal+console

[Install]
WantedBy=multi-user.target
`
	if err := writeFile(rootfs, "/usr/lib/systemd/system/nosaic-selftest.service",
		selftestUnit, 0o644); err != nil {
		return err
	}
	link := filepath.Join(wants, "nosaic-selftest.service")
	_ = os.Remove(link)
	if err := os.Symlink("/usr/lib/systemd/system/nosaic-selftest.service", link); err != nil {
		return err
	}

	// What systemd boots into. Without this it looks for default.target and
	// finds nothing, which is a failure at PID 1 with an emergency shell.
	def := filepath.Join(rootfs, "etc", "systemd", "system", "default.target")
	_ = os.Remove(def)
	if err := os.Symlink("/usr/lib/systemd/system/multi-user.target", def); err != nil {
		return err
	}

	// An empty machine-id means "first boot": systemd populates it and, on a
	// read-only image, keeps it in the overlay. Omitting the file entirely is
	// what makes systemd refuse to proceed on some configurations.
	if err := writeFile(rootfs, "/etc/machine-id", "", 0o444); err != nil {
		return err
	}

	return writeFile(rootfs, "/etc/hostname", "nosaic\n", 0o644)
}
