#!/bin/sh
# Generate this board's SDK port map from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# The SDK cannot bring up a single port without knowing which logical port is
# wired to which physical SerDes lane. That is a fact about the board, and no
# public document publishes it for this machine: it is a 2017-era EOS-only box,
# absent from Arista's open SONiC platform tree and from sonic-buildimage.
#
# So it has to be read from the vendor's software on the machine that has it.
# That makes the result vendor-derived, which is why NOSaic ships this
# generator and not its output. You run it once against your own switch and
# the map stays yours.
#
# This is the same arrangement EdgeNOS uses on this board, and the approach is
# taken from its platform/arista-7050sx2-72q/tools/mkconfigbcm.sh.
#
# WHY GUESSING DOES NOT WORK
#
# The map is not an offset. On this board Ethernet1..20 sit on physical lanes
# 13..32, Ethernet21..48 on 41..68, and the QSFP cages are not even in order --
# Ethernet50 occupies lanes 69..72, below Ethernet49's 73..76. A sequential map
# satisfies the chip's bandwidth rules and reaches none of the right cages.
#
# READ-ONLY. `show platform trident system detail` is a show command. Nothing
# is written to the switch, which may be carrying traffic while this runs.
#
# USAGE
#   ./mkportmap.sh <switch-ip> > portmap.conf     # over the network, needs sshpass
#   ./mkportmap.sh --stdin < captured.txt > portmap.conf
#
# The second form takes the command's output from anywhere -- a serial console
# session, for instance, which is how it is done on a switch with no management
# address configured.
#
# Environment: SW_USER (default admin), SW_PW (default arista).
set -u

emit() {
    # EOS prints one row per logical port:
    #
    #     Intf          Chip       ModId  Logical  Physical  MMU
    #   Ethernet1   Linecard0/0      1       1        13      1
    #   Ethernet49/1 Linecard0/0     1      49        73     66
    #
    # Logical is the SDK's port number and Physical is the lane it wants in
    # portmap_<logical>=<physical>:<speed>. Unconnected ports are the chip's
    # own spares and are skipped: they have no cage and configuring them would
    # spend quad bandwidth on nothing.
    awk '
        $1 ~ /^Ethernet[0-9]/ && NF >= 6 {
            intf = $1; logical = $(NF-2); physical = $(NF-1); mmu = $NF
            if (logical !~ /^[0-9]+$/ || physical !~ /^[0-9]+$/) next
            # A slashed name is one lane of a breakout cage; both are 10G here.
            printf "portmap_%s=%s:10\t# %s (mmu %s)\n", logical, physical, intf, mmu
            n++
        }
        END {
            if (n == 0) {
                print "mkportmap: no port rows found in the input" > "/dev/stderr"
                exit 1
            }
            printf "# %d ports\n", n
        }
    '
}

cat <<'HDR'
# Port map for this switch, generated by tools/mkportmap.sh.
#
# GENERATED FROM YOUR OWN SWITCH. Not shipped with NOSaic: the numbers are the
# vendor's, read from the machine that already has them. The generator is ours;
# this output is yours.
#
# Regenerate after any port-profile change (breakout, speed), because the
# logical-to-physical mapping moves with it.
HDR

if [ "${1:-}" = "--stdin" ]; then
    emit
else
    SW=${1:?usage: mkportmap.sh <switch-ip>   |   mkportmap.sh --stdin < captured.txt}
    USER=${SW_USER:-admin}
    PW=${SW_PW:-arista}
    sshpass -p "$PW" ssh \
        -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        -o ConnectTimeout=10 -o HostKeyAlgorithms=+ssh-rsa \
        -o PubkeyAcceptedKeyTypes=+ssh-rsa \
        -o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 \
        "$USER@$SW" "enable
terminal length 0
show platform trident system detail" 2>/dev/null | tr -d '\r' | emit
fi
