#!/bin/sh
# Generate this board's SDK port map from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# The SDK cannot bring up a single port without knowing which logical port is
# wired to which physical SerDes lane. That is a fact about the board, and no
# public document publishes it for this machine: it is a 2017-era EOS-only box,
# absent from Arista's open SONiC platform tree and from sonic-buildimage.
#
# So it has to be read from the vendor's software on the machine that has it.
# That makes the result vendor-derived, which is why NOSaic ships this
# generator and not its output. You run it once against your own switch and
# the map stays yours.
#
# This is the same arrangement EdgeNOS uses on this board, and the approach is
# taken from its platform/arista-7050sx2-72q/tools/mkconfigbcm.sh.
#
# WHY GUESSING DOES NOT WORK
#
# The map is not an offset. On this board Ethernet1..20 sit on physical lanes
# 13..32, Ethernet21..48 on 41..68, and the QSFP cages are not even in order --
# Ethernet50 occupies lanes 69..72, below Ethernet49's 73..76. A sequential map
# satisfies the chip's bandwidth rules and reaches none of the right cages.
#
# READ-ONLY. `show platform trident system detail` is a show command. Nothing
# is written to the switch, which may be carrying traffic while this runs.
#
# USAGE
#   ./mkportmap.sh <switch-ip> > portmap.conf     # over the network, needs sshpass
#   ./mkportmap.sh --stdin < captured.txt > portmap.conf
#
# Environment: SFP_CAGES (default 48) is how many front-panel cages are SFP+.
#
# The second form takes the command's output from anywhere -- a serial console
# session, for instance, which is how it is done on a switch with no management
# address configured.
#
# Environment: SW_USER (default admin), SW_PW (default arista).
set -u

# How many front-panel cages are SFP+. Above this they are QSFP+, which is
# board data and the reason this generator lives in the board directory.
SFP_CAGES=${SFP_CAGES:-48}

emit() {
    # EOS prints one row per logical port:
    #
    #     Intf          Chip       ModId  Logical  Physical  MMU
    #   Ethernet1   Linecard0/0      1       1        13      1
    #   Ethernet49/1 Linecard0/0     1      49        73     66
    #
    # Logical is the SDK's port number and Physical is the lane it wants in
    # portmap_<logical>=<physical>:<speed>.
    #
    # SPEED COMES FROM HOW THE CAGE IS CONFIGURED, NOT FROM THE CAGE TYPE.
    # A QSFP+ cage is either one 40G port or four 10G ports, and EOS names it
    # accordingly: Ethernet49/1..4 when broken out, plain Ethernet49 when it is
    # a single 40G. So a slashed name is one 10G lane of a breakout, and an
    # unslashed name above the SFP+ range is a whole 40G cage.
    #
    # This matters because the two are not interchangeable. Mapping a 40G cage
    # as four 10G lanes spends four logical ports on hardware that has one, and
    # the chip accepts it -- a wrong port map is silently inert rather than
    # rejected.
    #
    # Regenerate after changing any breakout, because the logical numbering
    # moves with it.
    awk -v sfp="$SFP_CAGES" '
        $1 ~ /^Ethernet[0-9]/ && NF >= 6 {
            intf = $1; logical = $(NF-2); physical = $(NF-1); mmu = $NF
            if (logical !~ /^[0-9]+$/ || physical !~ /^[0-9]+$/) next

            cage = intf; sub(/^Ethernet/, "", cage); sub(/\/.*/, "", cage)
            if (intf ~ /\//) {
                speed = 10; kind = "breakout lane"
            } else if (cage + 0 > sfp + 0) {
                speed = 40; kind = "40G cage"; forty++
            } else {
                speed = 10; kind = "SFP+"
            }
            # A logical port appearing twice means the input is not a single
            # consistent view of the switch -- a spliced capture, or two runs
            # concatenated. It would produce two portmap_ lines for one port,
            # and only one of them can be right.
            if (logical in seen) {
                printf "mkportmap: logical port %s appears twice (%s and %s); the input is not one consistent capture\n",
                       logical, seen[logical], intf > "/dev/stderr"
                bad++
            }
            seen[logical] = intf

            printf "portmap_%s=%s:%d\t# %s, %s (mmu %s)\n",
                   logical, physical, speed, intf, kind, mmu
            n++
        }
        END {
            if (n == 0) {
                print "mkportmap: no port rows found in the input" > "/dev/stderr"
                exit 1
            }
            if (bad) {
                printf "mkportmap: %d duplicate logical port(s); refusing to emit a map that cannot be right\n",
                       bad > "/dev/stderr"
                exit 1
            }
            printf "# %d ports", n
            if (forty) printf ", %d of them 40G cages", forty
            printf "\n"
        }
    '
}

cat <<'HDR'
# Port map for this switch, generated by tools/mkportmap.sh.
#
# GENERATED FROM YOUR OWN SWITCH. Not shipped with NOSaic: the numbers are the
# vendor's, read from the machine that already has them. The generator is ours;
# this output is yours.
#
# Regenerate after any port-profile change (breakout, speed), because the
# logical-to-physical mapping moves with it.
HDR

# Everything below is derived from the port list rather than read from the
# switch, so it is emitted alongside the map rather than shipped: it depends on
# how many ports this switch has and how they are numbered.
derived() {
    awk '
        /^portmap_/ {
            split($1, a, "=");  logical = substr(a[1], 9)
            ports[++n] = logical
            if (logical + 0 > max) max = logical + 0
        }
        END {
            if (n == 0) exit 0
            print ""
            print "# Which logical ports are 10G (xe). The SDK wants a bitmap,"
            print "# bit N meaning logical port N. Derived from the map above so"
            print "# a board with a different port count still comes out right."
            # awk has no shifts portable enough to trust here, so build the hex
            # digits directly: nibble i holds bits 4i..4i+3.
            for (i = 1; i <= n; i++) nib[int(ports[i] / 4)] += 2 ^ (ports[i] % 4)
            hex = ""
            for (i = int(max / 4); i >= 0; i--) {
                v = nib[i] + 0
                hex = hex substr("0123456789abcdef", v + 1, 1)
            }
            sub(/^0+/, "", hex)
            printf "pbmp_xport_xe=0x%s\n", hex

            print ""
            print "# Per-lane SerDes: decision-feedback equalisation on, optical"
            print "# media. Not board-specific and not read from the switch --"
            print "# every front-panel cage here is SFP+ or QSFP optical, and DFE"
            print "# is what the SDK wants for a passive optical link. Without it"
            print "# a link comes up and the frames arriving over it do not"
            print "# decode."
            for (i = 1; i <= n; i++) {
                printf "serdes_lane_config_dfe_%s=on\n", ports[i]
                printf "serdes_lane_config_media_type_%s=optics\n", ports[i]
            }
        }
    '
}

if [ "${1:-}" = "--stdin" ]; then
    TMP=$(mktemp); trap 'rm -f "$TMP"' EXIT
    emit > "$TMP" || exit 1
    cat "$TMP"; derived < "$TMP"
    exit 0
else
    SW=${1:?usage: mkportmap.sh <switch-ip>   |   mkportmap.sh --stdin < captured.txt}
    TMP0=$(mktemp)
    USER=${SW_USER:-admin}
    PW=${SW_PW:-arista}
    sshpass -p "$PW" ssh \
        -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        -o ConnectTimeout=10 -o HostKeyAlgorithms=+ssh-rsa \
        -o PubkeyAcceptedKeyTypes=+ssh-rsa \
        -o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 \
        "$USER@$SW" "enable
terminal length 0
show platform trident system detail" 2>/dev/null | tr -d '\r' > "$TMP0"
    TMP=$(mktemp); trap 'rm -f "$TMP" "$TMP0"' EXIT
    emit < "$TMP0" > "$TMP" || exit 1
    cat "$TMP"; derived < "$TMP"
fi
