#!/bin/bash
# Generate this board's SerDes polarity table from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# Getting polarity wrong does not break the link. It brings the link UP and
# makes every frame garbage: inverting a 64b/66b stream turns the sync header
# 01 into 10, which is also legal, so the receiver locks happily onto nonsense
# and reports no errors. A switch healthy at every layer that moves no traffic.
#
# On this board roughly 30 TX and 32 RX lanes are inverted -- the PCB swaps the
# differential pair, lane by lane -- and no public document says which. It is a
# property of the board, but the only practical way to read it is to ask the
# vendor's software what it programmed, which makes the result vendor-derived.
# NOSaic therefore ships this generator and not its output.
#
# Same arrangement as tools/mkportmap.sh. The approach and the register
# addresses are taken from EdgeNOS's platform/arista-7050sx2-72q/tools/
# mkpolarity.sh, which solved this first.
#
# READ-ONLY. Every command issued is a register read.
#
#   ⚠ Uses `phy raw sbus`. Do NOT substitute `getreg` -- a blind getreg sweep
#     wedged this box hard enough to need a physical power cycle.
#
# USAGE
#   ./mkpolarity.sh <switch-ip> > polarity.conf
#
# Environment: SW_USER (default admin), SW_PW (default arista).
set -u
SW=${1:?usage: mkpolarity.sh <switch-ip>}
USER=${SW_USER:-admin}
PW=${SW_PW:-arista}
MODE=${MODE:-"platform trident shell"}

SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
-o ConnectTimeout=10 -o HostKeyAlgorithms=+ssh-rsa
-o PubkeyAcceptedKeyTypes=+ssh-rsa
-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"

# EOS silently drops most diag commands when they arrive as an SSH exec-mode
# string -- no error and no output, which reads exactly like "the shell cannot
# do that". They have to be staged on the switch and run through on-box
# FastCli. base64 avoids quoting through two shell layers; the mode line must
# lead and `exit` must trail or FastCli hangs holding the shell open.
bsh() {
    local b
    b=$({ echo "$MODE"; cat; echo "exit"; } | base64 -w0)
    sshpass -p "$PW" ssh $SSHOPTS "$USER@$SW" "enable
bash echo $b | base64 -d > /tmp/mkpol.txt
bash cd /tmp && FastCli -p 15 -c \"\$(cat /tmp/mkpol.txt)\" 2>&1" 2>/dev/null | tr -d '\r'
}

# ---- pass 1: which macro and lane is each logical port on? -----------------
#
#   Phy mapping dump:
#         port   id0   id1  addr iaddr                    name           timeout
#     xe0(  1)  600d  8770    8d    8d           TSCE4-A0/03/1     250000
#
# The bracketed number is the logical port the polarity property is keyed on;
# `addr` is the SBUS macro; the digit after the last / in the name is the lane.
# Taking id1 (the PHY part number) instead of addr asks for a macro that does
# not exist, and every read then returns nothing.
MAP=$(printf 'phy info\n' | bsh | awk '
    /^ *xe[0-9]+\( *[0-9]+\)/ {
        p = $0; sub(/.*\( */, "", p); sub(/\).*/, "", p)
        lane = ""
        for (i = 1; i <= NF; i++) if ($i ~ /\//) { lane = $i; break }
        sub(/.*\//, "", lane)
        if (p != "" && $5 ~ /^[0-9a-f]+$/ && lane ~ /^[0-3]$/) print p, $5, lane
    }')

[ -n "$MAP" ] || { echo "mkpolarity: could not read 'phy info' from $SW" >&2; exit 1; }
NPORT=$(printf '%s\n' "$MAP" | wc -l)

# ---- pass 2: both polarity bits for every (macro, lane) -------------------
#
# One session for all of them: a round trip per register would be hundreds of
# SSH logins.
#
#   TX_PMD_DP_INVERT   TLB_TX_TLB_TX_MISC_CFG (0xd0e3) bit 0
#   RX_PMD_DP_INVERT   TLB_RX_TLB_RX_MISC_CFG (0xd0d3) bit 0
CMDS=$(printf '%s\n' "$MAP" | while read -r port macro lane; do
           echo "phy raw sbus 0x$macro 1.$lane 0xd0e3"
           echo "phy raw sbus 0x$macro 1.$lane 0xd0d3"
       done)

VALS=$(printf '%s\n' "$CMDS" | bsh | grep -oE '0x[0-9a-f]+: *0x[0-9a-f]+' \
       | sed -E 's/.*: *0x0*([0-9a-f]+)/\1/; s/^$/0/')

NVAL=$(printf '%s\n' "$VALS" | grep -c .)
if [ "$NVAL" -ne $((NPORT * 2)) ]; then
    echo "mkpolarity: asked for $((NPORT * 2)) registers, got $NVAL answers." >&2
    echo "  Refusing to emit a table that may be misaligned. A wrong polarity" >&2
    echo "  table brings links up carrying garbage, which is worse than none." >&2
    exit 1
fi

printf '# SerDes polarity for this board, generated by tools/mkpolarity.sh.\n'
printf '# Source switch: %s, read %s\n' "$SW" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
printf '# %d ports read from the running chip.\n#\n' "$NPORT"
printf '# GENERATED FROM YOUR OWN SWITCH, and not shipped with NOSaic: the\n'
printf '# numbers are the vendor'"'"'s, read from the machine that has them.\n#\n'
printf '# Read LIVE rather than from a capture of bring-up. A capture of this\n'
printf '# board shows these written as 0 with a later phase setting them, and\n'
printf '# reasoning from the capture produced a confidently wrong answer once.\n'

TXO=""; RXO=""; ntx=0; nrx=0; i=1
while read -r port macro lane; do
    tx=$(printf '%s\n' "$VALS" | sed -n "${i}p"); i=$((i+1))
    rx=$(printf '%s\n' "$VALS" | sed -n "${i}p"); i=$((i+1))
    [ $(( 0x${tx:-0} & 1 )) -eq 1 ] && {
        TXO="$TXO$(printf 'phy_xaui_tx_polarity_flip_%s=0x1\t# macro 0x%s lane %s' "$port" "$macro" "$lane")"$'\n'
        ntx=$((ntx+1)); }
    [ $(( 0x${rx:-0} & 1 )) -eq 1 ] && {
        RXO="$RXO$(printf 'phy_xaui_rx_polarity_flip_%s=0x1\t# macro 0x%s lane %s' "$port" "$macro" "$lane")"$'\n'
        nrx=$((nrx+1)); }
done <<< "$MAP"

printf '\n# --- TX polarity: %d inverted lanes ---\n' "$ntx"
printf '%s' "$TXO"
printf '\n# --- RX polarity: %d inverted lanes ---\n' "$nrx"
printf '%s' "$RXO"
