#!/bin/bash
# Generate this board's chassis status LED map from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# The chassis lamps -- system status, the two PSU lamps, the fan lamp and the
# blue locator beacon -- are not on the SCD. They are registers on the same CPLD
# that runs the fans, and unlike the SCD offsets and the fan registers, these
# five are NOT in anything the vendor publishes: they come from a board
# description file that ships inside the vendor's OS. They are board data, but
# they are the vendor's board data, so NOSaic ships this generator and not its
# output.
#
# Same arrangement as tools/mkportmap.sh and tools/mkpolarity.sh, and the same
# reason. The approach is taken from the reverse-engineering tree's
# tools/mkstatusleds.sh, which solved this first; this one emits NOSaic's
# key=value config instead of a C header.
#
# Everything the mechanism needs beyond these five offsets is already public:
# the CPLD answers at 0x60 on SMBus accelerator 0 bus 0, which the vendor's own
# published arista/platforms/cpu/crow.py gives as
# CrowFanCpld addr=scd.i2cAddr(bus, 0x60).
#
# USAGE
#   ./mkstatusleds.sh <switch-ip> > ../config/statusleds.conf
#
# Environment: SW_USER (default admin), SW_PW (default arista).
#
# READ-ONLY. This reads three text files off the switch over SSH. It issues no
# register access at all, let alone to the CPLD -- sweeping that part has
# powered a box off twice, and nothing here goes near it.
set -u
SW=${1:?usage: mkstatusleds.sh <switch-ip> > ../config/statusleds.conf}
USER=${SW_USER:-admin}
PW=${SW_PW:-arista}

SSHOPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
-o ConnectTimeout=10 -o HostKeyAlgorithms=+ssh-rsa
-o PubkeyAcceptedKeyTypes=+ssh-rsa
-o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1"

sw() { sshpass -p "$PW" ssh $SSHOPTS "$USER@$SW" "enable
bash $*" 2>/dev/null | tr -d '\r'; }

die() { echo "mkstatusleds: $*" >&2; exit 1; }

# 1. Which board is this? The SID in the programmed prefdl IS the board
#    description's name.
SID=$(sw "grep -i '^SID:' /etc/prefdl | head -1 | cut -d: -f2 | tr -d ' '")
[ -n "$SID" ] || die "could not read SID from /etc/prefdl on $SW"

# 2. Which classes does it inherit? The plugin for the CPU family maps
#    (SID, hwrev) -> a list of classes, and the LED table lives in a PARENT
#    rather than in the board's own file -- which is what made this hard to
#    find. Search every plugin rather than assuming the family.
CLASSES=$(sw "grep -h \"'$SID'\" -A3 /usr/lib/python*/site-packages/GenfdlPlugin/*.py \
             | tr -d \"\\n\" | tr ']' '\\n' | grep -m1 \"'$SID'\" | tr -d \"[]',\"")
[ -n "$CLASSES" ] || die "no board-description entry for SID '$SID'"

# 3. The LED table. addLeds() lists ( description, addr, greenBit, redBit ) and
#    a comment gives the blue beacon's own register. Take the first class that
#    has one -- the board's own file inherits it.
TABLE=""
for c in $CLASSES; do
    case "$c" in *:*|*\(*) continue;; esac
    t=$(sw "sed -n '/def addLeds/,/def /p' /usr/share/NorCal/$c.fdl 2>/dev/null")
    if echo "$t" | grep -q 'cpldLedBlock\|cpldLedInfo'; then TABLE="$t"; FDL="$c"; break; fi
done
[ -n "$TABLE" ] || die "no addLeds() with a CPLD LED table in: $CLASSES"

get()   { echo "$TABLE" | grep -oE "\(\s*\"$1\"\s*,\s*0x[0-9a-fA-F]+\s*,\s*[0-9]+\s*,\s*[0-9]+\s*\)" | head -1; }
field() { echo "$1" | tr -d '() "' | cut -d, -f"$2"; }

S=$(get Status1); P1=$(get PowerSupply1); P2=$(get PowerSupply2); F=$(get MultiFan1)
[ -n "$S" ] || die "no Status1 entry in $FDL addLeds()"

BEACON=$(echo "$TABLE" | grep -oE 'blueLedOffset\s*=\s*0x[0-9a-fA-F]+' | grep -oE '0x[0-9a-fA-F]+' | head -1)
BEACONBIT=$(echo "$TABLE" | grep -oE 'blueBit\s*=\s*[0-9]+' | grep -oE '[0-9]+$' | head -1)
: "${BEACONBIT:=0}"

emit() { [ -n "$2" ] && printf '%-10s= %s\n' "$1" "$(field "$2" 2)"; }

cat <<EOF
# Chassis status LED map for $SID, read from $FDL.fdl on a live switch.
#
# GENERATED by platform/arista-7050sx2-72q/tools/mkstatusleds.sh
# -- do not edit, and do not commit. These offsets are vendor board-description
# data; the tool that regenerates them is what ships. Rerun it against your own
# switch to recreate this file.
#
# The image builder copies platform/<board>/config/ into /etc/nosaic, where the
# platform HAL reads it. Without this file the chassis lamps are reported as
# unconfigured and are never written, which is deliberate: a panel driven from a
# guessed map would be a switch telling an operator something false about its
# own health.
EOF
emit status "$S"
emit psu1   "$P1"
emit psu2   "$P2"
emit fan    "$F"
printf '%-10s= %s\n' beacon "${BEACON:-}"
printf '\n# Both colours live in one register: a set bit lights that emitter, and\n'
printf '# both set shows amber. Note this is the OPPOSITE of the fan-tray lamps on\n'
printf '# the same part, which the vendor drives active LOW.\n'
printf '%-10s= %s\n' green_bit "$(field "$S" 3)"
printf '%-10s= %s\n' red_bit   "$(field "$S" 4)"
printf '%-10s= %s\n' blue_bit  "$BEACONBIT"
