#!/bin/sh
# Generate this board's DS100KR800 repeater tuning from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# A TI DS100KR800 sits between the switch chip's SerDes and the last two QSFP
# cages. Out of reset but unprogrammed it conditions nothing, and because its
# eight channels carry those two ports in the host-to-module direction only,
# the symptom is one-sided: the cage receives its neighbour perfectly, the
# neighbour never sees us, and neither end reports an error.
#
# The register offsets are public -- TI's SNLS340E, Table 6 -- and live in the
# driver. The VALUES are output amplitude and de-emphasis tuned for one PCB's
# trace lengths. They are in the board's own description file, they are the
# vendor's rather than ours, and so NOSaic ships this generator and not its
# output. Run it once against your own switch and the result stays yours.
#
# WHY GUESSING DOES NOT WORK
#
# An unprogrammed repeater is a dead port: obvious, and it will be found. A
# wrongly programmed one is a link that passes traffic until temperature or a
# longer cable takes it over the edge. Do not invent these numbers.
#
# USAGE
#   ./mkretimer.sh --stdin < fdl.txt   > retimer.conf
#   ./mkretimer.sh <switch-ip>         > retimer.conf
#
# The switch must be running the vendor OS, which is where the description file
# is readable.
set -u

usage() {
	echo "usage: $0 --stdin < fdl.txt > retimer.conf" >&2
	echo "       $0 <switch-ip>       > retimer.conf" >&2
	exit 2
}
[ $# -ge 1 ] || usage

if [ "$1" = "--stdin" ]; then
	src=$(cat)
else
	command -v sshpass >/dev/null 2>&1 || {
		echo "$0: sshpass is not installed; capture /etc/fdl by hand and use --stdin" >&2
		exit 1
	}
	src=$(sshpass -p "${SW_PW:-arista}" ssh -o StrictHostKeyChecking=no \
		"${SW_USER:-admin}@$1" 'enable
bash cat /etc/fdl' 2>/dev/null) || {
		echo "$0: could not read the description file from $1" >&2
		exit 1
	}
fi
[ -n "$src" ] || { echo "$0: no input" >&2; exit 1; }

# The description file gives names and decimal values. Pull the repeater's
# block; the names are the vendor's own.
get() {
	printf '%s\n' "$src" |
		sed -n "s/.*'\\{0,1\\}$1'\\{0,1\\}[^0-9-]\\{1,\\}\\([0-9]\\{1,\\}\\).*/\\1/p" |
		head -1
}
pin=$(get pinControl);      crc=$(get disableCrc)
eq=$(get rxEqualization)
vod=$(get outputAmplitude);  dem=$(get txDeEmphasis)

# ⚠ Channels 0-3 and 4-7 are tuned SEPARATELY -- one port's worth of lanes
# each -- so the file records both. Where the description gives a single value
# per group, the second occurrence is the high group.
vod2=$(printf '%s\n' "$src" | sed -n "s/.*outputAmplitude[^0-9]\{1,\}\([0-9]\{1,\}\).*/\1/p" | sed -n 2p)
dem2=$(printf '%s\n' "$src" | sed -n "s/.*txDeEmphasis[^0-9]\{1,\}\([0-9]\{1,\}\).*/\1/p" | sed -n 2p)
: "${vod2:=$vod}" "${dem2:=$dem}"

for v in pin crc eq vod dem; do
	eval "val=\$$v"
	[ -n "$val" ] || { echo "$0: could not read $v from the description file" >&2; exit 1; }
done

printf '# Generated by mkretimer.sh from this switch. Do not commit.\n'
printf '# DS100KR800 tuning for one physical board.\n'
printf 'pin_control = %d\n' "$pin"
printf 'disable_crc = %d\n' "$crc"
printf 'vod_low     = %d\n' "$vod"
printf 'vod_high    = %d\n' "$vod2"
printf 'dem_low     = %d\n' "$dem"
printf 'dem_high    = %d\n' "$dem2"
printf 'eq          = %d\n' "$eq"

echo "$0: repeater tuning written (amplitude $vod/$vod2, de-emphasis $dem/$dem2)" >&2
