#!/bin/sh
# Generate this board's SerDes transmit equalisation from YOUR OWN switch.
#
# WHY THIS EXISTS
#
# The SDK transmits with its own compiled-in tap defaults, which are not this
# board's. The board's description file gives a per-port profile -- pre, main
# and post tap, plus driver current -- tuned for the PCB's trace lengths, and
# without it a 40G cage links while the far end reports a remote fault: our
# receive is clean, our transmit is not accepted, and no counter on either side
# shows an error.
#
# Those numbers are the board vendor's, so NOSaic ships this generator and not
# its output -- the same arrangement as the port map, the polarity table and
# the repeater tuning.
#
# ⚠ BIT 15 IS NOT OPTIONAL.
#
# The packing is post<<10 | main<<4 | pre. A 40G CR4 port uses the SDK's KR tap
# set, and serdes_preemphasis only reaches the plain tap register; bit 15 is
# the tap-force bit that makes it reach the set actually in use. Without it the
# property is accepted, the pre-tap appears to take because it happens to be
# the same in both sets, and main and post do not move -- which reads as "that
# setting did not help" rather than "that setting did not apply".
#
# USAGE
#   ./mkserdes.sh --stdin < fdl.txt  > serdes.conf
#   ./mkserdes.sh <switch-ip>        > serdes.conf
set -u

usage() {
	echo "usage: $0 --stdin < fdl.txt > serdes.conf" >&2
	echo "       $0 <switch-ip>       > serdes.conf" >&2
	exit 2
}
[ $# -ge 1 ] || usage

if [ "$1" = "--stdin" ]; then
	src=$(cat)
else
	command -v sshpass >/dev/null 2>&1 || {
		echo "$0: sshpass is not installed; capture /etc/fdl by hand and use --stdin" >&2
		exit 1
	}
	src=$(sshpass -p "${SW_PW:-arista}" ssh -o StrictHostKeyChecking=no \
		"${SW_USER:-admin}@$1" 'enable
bash cat /etc/fdl' 2>/dev/null) || {
		echo "$0: could not read the description file from $1" >&2
		exit 1
	}
fi
[ -n "$src" ] || { echo "$0: no input" >&2; exit 1; }

get() {
	printf '%s\n' "$src" |
		sed -n "s/.*'\\{0,1\\}$1'\\{0,1\\}[^0-9-]\\{1,\\}\\([0-9]\\{1,\\}\\).*/\\1/p" |
		head -1
}
pre=$(get preTap); main=$(get mainTap); post=$(get postTap)
for v in pre main post; do
	eval "val=\$$v"
	[ -n "$val" ] || { echo "$0: could not read ${v}Tap from the description file" >&2; exit 1; }
done

# The cage this profile belongs to. Et52 is SDK logical port 61 -- a QSFP cage
# occupies four consecutive logical ports even as one 40G port, so it is not 52.
PORT="${SERDES_PORT:-61}"

packed=$(( (post << 10) | (main << 4) | pre ))
forced=$(printf '0x%04X' $(( packed | 0x8000 )))

printf '# Generated by mkserdes.sh from this switch. Do not commit.\n'
printf '# SerDes transmit equalisation for one physical board.\n'
for lane in 0 1 2 3; do
	printf 'serdes_preemphasis_lane%d_%s.0=%s\n' "$lane" "$PORT" "$forced"
done
for lane in 0 1 2 3; do
	printf 'serdes_driver_current_lane%d_%s.0=0\n' "$lane" "$PORT"
done

echo "$0: port $PORT taps pre=$pre main=$main post=$post -> $forced (tap-force set)" >&2
