package pkgbuild

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
)

// runCMakeBuild configures, compiles and stage-installs a cmake package.
//
// Like meson, cmake does not infer a cross-compile from the environment: given
// only CC and CFLAGS it still probes the machine it is running on, decides it
// can execute what it compiles, and produces a package for the wrong CPU. It
// needs a toolchain file. That file is generated from the architecture
// definition rather than committed, so it cannot drift from the toolchain it
// describes.
func runCMakeBuild(o Options, srcDir, stage string) error {
	tf := filepath.Join(srcDir, "nosaic-toolchain.cmake")
	if err := os.WriteFile(tf, []byte(cmakeToolchainFile(o)), 0o644); err != nil {
		return err
	}

	build := filepath.Join(srcDir, "build")
	args := []string{
		"-S", srcDir,
		"-B", build,
		"-DCMAKE_TOOLCHAIN_FILE=" + tf,
		"-DCMAKE_INSTALL_PREFIX=" + prefix,
		"-DCMAKE_BUILD_TYPE=Release",
	}
	for _, a := range o.Recipe.Build.Configure {
		args = append(args, expand(o, a))
	}
	env := buildEnv(o)
	if err := run(o, srcDir, env, "cmake", args...); err != nil {
		return err
	}
	if err := run(o, srcDir, env, "cmake", "--build", build,
		"--parallel", strconv.Itoa(o.Jobs)); err != nil {
		return err
	}
	// --prefix is not repeated here: it would override the DESTDIR-relative
	// layout the configure step established.
	installEnv := append(env, "DESTDIR="+stage)
	return run(o, srcDir, installEnv, "cmake", "--install", build)
}

func cmakeToolchainFile(o Options) string {
	tc := filepath.Join(o.Root, "toolchain", o.Arch.ID)
	bin := filepath.Join(tc, "bin")
	t := o.Arch.Triple
	staging := filepath.Join(o.Root, ".cache", "sysroot", o.Arch.ID)

	proc := o.Arch.MesonCPU
	if proc == "" {
		proc = o.Arch.ID
	}

	// CMAKE_FIND_ROOT_PATH plus the three MODE settings are what keep the
	// build host out of the result: without them find_library and find_path
	// search / as well, so a header present on the builder and absent in the
	// staging sysroot enables a feature that cannot compile for the target.
	// Programs are the deliberate exception -- a build genuinely does need to
	// run host tools.
	return fmt.Sprintf(`# Generated by nosaic. Do not edit: it is written from
# arch/%s/arch.yml so it cannot disagree with the toolchain it describes.
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR %s)

set(CMAKE_C_COMPILER   %s/%s-gcc)
set(CMAKE_CXX_COMPILER %s/%s-g++)
set(CMAKE_AR           %s/%s-ar)
set(CMAKE_RANLIB       %s/%s-ranlib)
set(CMAKE_STRIP        %s/%s-strip)

set(CMAKE_SYSROOT %s)
set(CMAKE_FIND_ROOT_PATH %s)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# -rpath-link as well as -L, for the same reason the autotools path needs it:
# the -L paths are not searched for a shared object's own DT_NEEDED entries.
set(CMAKE_C_FLAGS_INIT "-O2 -pipe -I%s/usr/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-L%s/usr/lib -Wl,-rpath-link=%s/usr/lib")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-L%s/usr/lib -Wl,-rpath-link=%s/usr/lib")
`, o.Arch.ID, proc,
		bin, t, bin, t, bin, t, bin, t, bin, t,
		filepath.Join(tc, t, "sysroot"), staging,
		staging, staging, staging, staging, staging)
}
