package pkgbuild

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
)

// runMesonBuild configures, compiles and stage-installs a meson package.
//
// meson does not infer a cross-compile from the environment the way autotools
// does: it needs a cross file naming the tools and describing the target, and
// without one it will happily build for the machine it is running on. So the
// cross file is generated from the architecture definition rather than
// committed, which means it cannot drift from the toolchain it describes.
func runMesonBuild(o Options, srcDir, stage string) error {
	cross := filepath.Join(srcDir, "nosaic-cross.ini")
	if err := os.WriteFile(cross, []byte(mesonCrossFile(o)), 0o644); err != nil {
		return err
	}

	build := filepath.Join(srcDir, "build")
	args := []string{
		"setup", build,
		"--cross-file", cross,
		"--prefix", prefix,
		"--buildtype", "release",
		// No blanket --default-library here.
		//
		// It was set to static on the grounds that nothing on a switch needs
		// to relink against a library we built. That is a reasonable policy
		// and a bad default: systemd deliberately builds shared internal
		// libraries, and overriding that globally broke its linking. A
		// package that wants static can ask for it in its own recipe, where
		// the choice is visible next to the package it affects.
	}
	for _, a := range o.Recipe.Build.Configure {
		args = append(args, expand(o, a))
	}
	env := buildEnv(o)
	if err := run(o, srcDir, env, "meson", args...); err != nil {
		return err
	}
	if err := run(o, srcDir, env, "ninja", "-C", build, "-j"+strconv.Itoa(o.Jobs)); err != nil {
		return err
	}
	installEnv := append(env, "DESTDIR="+stage)
	return run(o, srcDir, installEnv, "ninja", "-C", build, "install")
}

func mesonCrossFile(o Options) string {
	tc := filepath.Join(o.Root, "toolchain", o.Arch.ID)
	bin := filepath.Join(tc, "bin")
	t := o.Arch.Triple
	cpu := o.Arch.MesonCPU
	if cpu == "" {
		cpu = o.Arch.ID
	}
	staging := filepath.Join(o.Root, ".cache", "sysroot", o.Arch.ID)

	// The staging paths are declared here rather than left to CFLAGS and
	// LDFLAGS in the environment.
	//
	// meson treats those environment variables as applying to the *build*
	// machine when a cross file is in use, so a dependency staged for the
	// target is visible while compiling and absent while linking. systemd got
	// as far as 1020 of 1495 objects before failing on a single undefined
	// libmount symbol that was present in the library all along.
	return fmt.Sprintf(`# Generated by nosaic. Do not edit: it is written from
# arch/%s/arch.yml so it cannot disagree with the toolchain it describes.
[built-in options]
c_args = ['-I%s/usr/include', '-O2', '-pipe']
cpp_args = ['-I%s/usr/include', '-O2', '-pipe']
# -rpath-link as well as -L: the -L paths are not searched for a shared
# object's own DT_NEEDED entries, so an executable linking against a staged
# library that needs another staged library fails without it.
c_link_args = ['-L%s/usr/lib', '-L%s/lib', '-Wl,-rpath-link=%s/usr/lib', '-Wl,-rpath-link=%s/lib']
cpp_link_args = ['-L%s/usr/lib', '-L%s/lib', '-Wl,-rpath-link=%s/usr/lib', '-Wl,-rpath-link=%s/lib']

[binaries]
c = '%s/%s-gcc'
cpp = '%s/%s-g++'
ar = '%s/%s-ar'
strip = '%s/%s-strip'
pkg-config = 'pkg-config'

[host_machine]
system = 'linux'
cpu_family = '%s'
cpu = '%s'
endian = '%s'
`, o.Arch.ID, staging, staging,
		staging, staging, staging, staging,
		staging, staging, staging, staging,
		bin, t, bin, t, bin, t, bin, t, cpu, o.Arch.ID, o.Arch.Endian)
}
